Azure/durabletask

- Framework/Test/OrchestrationTestHost.cs
Removed the line in OrchestrationTestHost which traces delay.  This normally causes very frequent tracing that bloats test logs.
> Removed delay tracing from OrchestrationTestHost

- Framework/ServiceBusOrchestrationService.cs
instead of null when none found
> return an empty list for 'all orchestration states'

- Framework/TaskActivityDispatcher.cs
- Framework/TaskOrchestrationDispatcher.cs
- Framework/TrackingDispatcher.cs
- Framework/Utils.cs
Added entity names in the message dead lettering logs. This will help in diagnosing the errors better.
> Adding entity name to dead lettered error message

- samples/DurableTask.Samples/Program.cs
- samples/DurableTask.Samples/Signal/SignalOrchestration.cs
- src/DurableTask.Framework/IOrchestrationServiceClient.cs
- src/DurableTask.Framework/ServiceBusOrchestrationService.cs
- src/DurableTask.Framework/Settings/ServiceBusOrchestrationServiceSettings.cs
- src/DurableTask.Framework/TaskHubClient.cs
- test/DurableTask.Framework.Tests/Mocks/LocalOrchestrationService.cs
- tools/DurableTask.props
A common pattern for long-running orchestrations is to create an orchestration then raise an event on it. This causes twice as many messages to service bus. This change will do this process in a batch send.
> Adding RaiseEvent to client for scalability, Allow creating queue with specific size

- Framework/Framework.csproj
- Framework/INameVersionObjectManager.cs
- Framework/NameVersionObjectManager.cs
- Framework/TaskActivityDispatcher.cs
- Framework/TaskHubWorker.cs
- Framework/TaskOrchestrationDispatcher.cs
- Framework/Test/FakeOrchestrationExecutor.cs
I am working on a large project that heavily depends on DurableTask. We now have >150 activity classes, and similarly >70 orchestration classes. Since this number is growing almost daily, we would like to use dependency injection, Autofac in our case, to produce ObjectCreator<T> instances. 
What seemed to be the most straight forward and least intrusive way to implement this is by allowing extensibility at the NameVersionObjectManager level, allowing us to produce a singleton NameVersionObjectManager implementation that relies on Autofac.
> Allow extensibility for the NameVersionObjectManager

- src/DurableTask.Emulator/LocalOrchestrationService.cs
Return null from GetOrchestrationStateAsync to be on par with SB; Add support for termination
> Merge alextolp/emulator

- Test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
- src/DurableTask.Core/Middleware/DispatchMiddlewareContext.cs
- src/DurableTask.Core/Middleware/DispatchMiddlewareDelegate.cs
- src/DurableTask.Core/Middleware/DispatchMiddlewarePipeline.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskHubWorker.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
This PR enables developers to add AspNetCore-style middleware to the task and activity dispatcher components.  This custom middleware executes after the dispatcher has loaded the activity/orchestration but before it runs the executor logic.
Adding middleware is as simple as this:
```cs
TaskHubWorker worker = ...;
worker.AddOrchestrationDispatcherMiddleware(async (context, next) =>
{
// pre-execute...
await next();
// post-execute...
});
worker.AddActivityDispatcherMiddleware(async (context, next) =>
{
// pre-execute...
await next();
// post-execute...
});
```
You can add as many delegates as you want and they will be executed in-order for each task/orchestration execution. The context object contains a property bag as well as a few useful items from the runtime, like the …
> Dispatcher middleware for task orchestrations and task activities

- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/FrameworkConstants.cs
- src/DurableTask.Core/History/GenericEvent.cs
- src/DurableTask.Core/History/HistoryStateEvent.cs
- src/DurableTask.Core/OrchestrationStateInstanceFilter.cs
- src/DurableTask.Core/OrchestrationStateNameVersionFilter.cs
- src/DurableTask.Core/OrchestrationStateQuery.cs
- src/DurableTask.Core/OrchestrationStateQueryFilter.cs
- src/DurableTask.Core/OrchestrationStateStatusFilter.cs
- src/DurableTask.Core/OrchestrationStateTimeRangeFilter.cs
- src/DurableTask.Core/Settings/TaskActivityDispatcherSettings.cs
- src/DurableTask.Core/Settings/TaskOrchestrationDispatcherSettings.cs
- src/DurableTask.Core/Settings/TrackingDispatcherSettings.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Core/Tracing/DefaultEventSource.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
- src/DurableTask.Emulator/LocalOrchestrationService.cs
- src/DurableTask.Emulator/PeekLockQueue.cs
- src/DurableTask.ServiceBus/ServiceBusConstants.cs
- src/DurableTask.ServiceBus/Settings/ServiceBusOrchestrationServiceSettings.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableInstanceStore.cs
- tools/DurableTask.props
Add package info for creating nuget packages including documentation.
Add missing XML docs on public classes.
Fix bug with RaiseEvent calling create orchestration causing unneeded jumpstart entry.
Always set mindatetime for storage instance store, not just for emulator.
> Add missing docs, package info and bugfixes

- src/DurableTask.Core/TaskOrchestrationContext.cs
Fix for the issue where issuing TerminateInstanceAsync twice from client before the orchestration is picked up by dispatcher leads to a blocked orchestration (the processing keeps abandoning the orchestration).
Only the first terminate request is honored and subsequent terminates are ignored. (That makes the fix simple and hopefully not a problematic behavior from user's perspective)
> Fix for the issue with multiple Terminate events in a single batch

- Test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/MessageData.cs
- src/DurableTask.AzureStorage/Monitoring/AzureStorageOrchestrationServiceStats.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
- src/DurableTask.AzureStorage/Monitoring/PerformanceHeartbeat.cs
- src/DurableTask.AzureStorage/Monitoring/ScaleAction.cs
- src/DurableTask.AzureStorage/Monitoring/ScaleRecommendation.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/PartitionManager.cs
- src/DurableTask.AzureStorage/ReceivedMessageContext.cs
- src/DurableTask.AzureStorage/Utils.cs
- src/DurableTask.Core/Stats/Counter.cs
- tools/DurableTask.props
This change is the initial work to enable dynamic scale-out for the Durable Task Framework in Azure Functions (i.e. *Durable Functions*).  It consists of two parts:
1. Created a `DisconnectedPerformanceMonitor` class which is responsible for examining queue metrics and making scale decisions. I call it "disconnected" because it's designed to be run outside of the task hub worker process. The intent is to run it in the Azure Scale Controller component.
2. Created a `AzureStorageOrchestrationServiceStats` and used it to track how often we do various operations against Azure Storage. This is intended to work just like `ServiceBusOrchestrationServiceStats`, but is specific to the Azure Storage provider.
The intent is to plug this new functionality into Azure Functions so that scale-out can …
> Azure Functions Consumption Plan integration

- src/DurableTask.Emulator/LocalOrchestrationService.cs
Cloning task session messages in the LocationOrchestrationService to avoid Collection was modified exception
> Clone task session messages in the LocalOrchestrationService

- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/RetryProxy.cs
- src/DurableTask.Emulator/DurableTask.Emulator.csproj
- tools/DurableTask.props
This change enables multi-targeting of `DurableTask.Core` to both .NET 4.5.1 (the existing target) as well as .NET Standard 2.0 for .NET Core support. This is needed for the Azure Functions Durable Task extension, which needs to support .NET Core. The code changes are influenced by the [existing PR for .NET Core support](https://github.com/Azure/durabletask/pull/110), but this PR is only concerned with `DurableTask.Core` and it involves multi-targeting rather than a wholesale move to .NET Standard 2.0.
I arbitrarily bumped the version to 2.1.0.0-preview, but we can discuss this. I suspect it will need to remain as a preview release until the non-production NuGet dependencies can be removed or replaced with non-prerelease dependencies.
This change does not currently contain any support for …
> Add multi-targeting support for .NET standard 2.0.

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
This PR address two issues with the Azure Storage provider found during stress testing:
1. Messages intended for completed instances were never being deleted and were being replayed indefinitely.  The fix was to refactor the code slightly to ensure these messages were deleted.
2. Eternal orchestrations were getting slower and slower until they could no longer run. This is because eternal orchestrations were forever appending new history state (no cleanup) and the instance query involved a full partition scan to find the correct execution. The fix was to change the RowKey column to be simply the sequence number and overwrite history data from previous generations, resulting in fixed-size partitions regardless of how many generations the orchestration executed.
These changes are isolated to …
> Azure Storage Provider: Reduce History Size for Eternal Orchestrations

- src/DurableTask.Core/TaskOrchestrationContext.cs
This fix addresses an issue brought up by Durable Functions customers: https://github.com/Azure/azure-functions-durable-extension/issues/146.
The issue happens when DTFx receives a terminate message in the same message batch that would normally complete the orchestration. The terminate action gets executed, but then the completion action also gets executed, resulting in a state corruption error:
```
TaskOrchestrationDispatcher-f79977801ceb41aa82701d473427e52b-0: Exception while processing workItem 87e126f0d4f54d9ca092bf67c10cf4e0 Exception: System.InvalidOperationException : Multiple ExecutionCompletedEvent found, potential corruption in state storage at DurableTask.Core.OrchestrationRuntimeState.SetMarkerEvents(HistoryEvent historyEvent)
at …
```
> Fix orchestration completion/termination race condition

- Framework/ServiceBusOrchestrationService.cs
Handle the case where orchestration termination and timer creation at the same time. 
newOrchestrationRuntimeState will be null when the orchestration is in terminated state. It will cause a null session id, which will fail the sending of the service bus messages
> Handle the case where orchestration termination and timer creation at the same time

- Framework/TaskActivityDispatcher.cs
- Framework/TaskOrchestrationDispatcher.cs
- Framework/TrackingDispatcher.cs
delay by the non transient error backoff on jsonserialization exceptions while processing work items to allow forward compatibility.
> delay by the non transient error backoff on jsonserialization exceptions 

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
- tools/DurableTask.props
- Incremented DurableTask.Core and DurableTask.ServiceBus to **2.0.0.5** and removed "-preview"
- Incremented DurableTask.AzureStorage to **1.2.0** and removed "-beta"
- Update DurableTask.Core netstandard2.0 nuget dependencies to non-preview versions
- Include symbols in DurableTask.Core nuget package (debugging is a huge pain without this)
> Remove preview labels

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.AzureStorage/AsyncAutoResetEvent.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
FYI @gled4er. Let me know if you think this fix will work. I haven't had a chance to test it yet, but it looks like we need a new test case which fans out to 100+ activity functions.
> Fix issue with ETag check when fanning out to 100+ parallel activities

- Framework/ServiceBusOrchestrationService.cs
Save parentInstance field in the instance store for newly created child orchestration instance
> Save parentInstance field in the instance store for newly created child orchestration instance

- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/StateMessage.cs
- src/DurableTask.ServiceBus/Common/ServiceBusUtils.cs
This is required for an upgrade path from DurableTask 1.0
> Add support for deserializing a statemessage from the service bus tracking queue

- samples/DurableTask.Samples/DurableTask.Samples.csproj
- src/DurableTask.Core/FrameworkConstants.cs
- src/DurableTask.ServiceBus/Common/ServiceBusUtils.cs
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
- src/DurableTask.ServiceBus/Settings/ServiceBusMessageSenderSettings.cs
- src/DurableTask.ServiceBus/Settings/ServiceBusOrchestrationServiceSettings.cs
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
- test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.csproj
This PR contains improvements suggested by this document from ServiceBus:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements
- introduce separate messaging factories for each Service Bus client connection
- set default client-side batching interval to 100 msecs.
- introduce a configuration setting for client-side batching
- upgrade to the latest .NET 4.5.1 SB NuGet pkg  - 4.1.3
> Service Bus client connection performance improvements

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
Hi @cgillum and @gled4er,
I open this pull request to start discussion the details. 
I have two topic to discuss. 
1. How many attribute do we need? 
In the OrchestrationState has a lot of members. Which attribute do we need for this purpose?
2. Style of Query
We'll full scan search for the instance table. Is it OK? or do we have any other clever way to fetch the on the fly instances? Currenty, I just return all record of the isntance table. 
This pull request is correspond to this issue. 
https://github.com/Azure/azure-functions-durable-extension/issues/316
> DurableTask.AzureStorage API to enumerate instances

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/ActivitySession.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/Session.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/PartitionManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Utils.cs
This addresses much of https://github.com/Azure/azure-functions-durable-extension/issues/326.
Summary of changes:
* The version of the DurableTask.AzureStorage nuget package is traced everywhere.
* Added several new traces to capture errors. Previously we didn't trace unhandled exceptions when calling storage, and this made diagnosing issues very painful. The exceptions do get traced to the DurableTask.Core provider, but those traces are very difficult to correlate back to specific customer incidents.
* Refactored message processing trace into two events (was previously just one) so we can see both when a message was dequeued and when it was scheduled for processing. In production we've seen a case where messages appear to be sent but never received, and this update will help us identify …
> DurableTask.AzureStorage ETW tracing improvements

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
Hello @cgillum,
I am opening this PR to give your early visibility on the first changes for [#339](https://github.com/Azure/azure-functions-durable-extension/issues/339).
Let me know if you spot something that it needs to be fixed immediately.
I plan to double check the code and add tests for the change next.
Thank you!
> Adding 4MB limit for Azure Storage Table batch insert

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
This is a revised version of a previous pull request: https://github.com/Azure/durabletask/pull/191.  After merging, I did some testing and found a few issues. This new version addresses those issues.
FYI @tohling, @gled4er
This addresses https://github.com/Azure/azure-functions-durable-extension/issues/339.
> DurableTask.AzureStorage: Alternate fix for the 4 MB max entity size which covers more scenarios.

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Emulator/DurableTask.Emulator.csproj
- tools/DurableTask.props
Updating to fix: 
Azure/azure-functions-durable-extension/issues/342 (Caused by breaking change from between Newtonsoft.Json 10.0.3 and 11.0.2)
Azure/azure-functions-durable-extension/issues/343 (Caused by mismatched WindowsAzure.Storage versions between Azure Functions host and DurableTask)
> Updated Newtonsoft.Json to v11.0.2, WindowsAzure.Storage to v8.6.0.

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/ActivitySession.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/Session.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/PartitionManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
- src/DurableTask.AzureStorage/Utils.cs
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Emulator/DurableTask.Emulator.csproj
- tools/DurableTask.props
> DurableTask.AzureStorage updates to master (#187)

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/WorkItemDispatcher.cs
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
This PR resolves https://github.com/Azure/durabletask/issues/106 as well as an existing TODO in the code.  It is also a prerequisite for fixing https://github.com/Azure/azure-functions-durable-extension/issues/348 and https://github.com/Azure/azure-functions-durable-extension/issues/344.
The current task hub worker shutdown logic is extremely slow because it depends on waiting for receive operations to time out. A simple "hello world" scenario where you create a task hub, start it, and shut it down, can take as long as 90 seconds. This might be acceptable if hosting on cloud services or VMs, but this is not acceptable when hosting in IIS-based platforms, like Azure App Service or Azure Functions.
In this PR, we introduce cancellation tokens into the shutdown logic. The work-item …
> Cancellation tokens in work-item dispatcher logic

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/WorkItemDispatcher.cs
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
This PR is intended to fix https://github.com/Azure/azure-functions-durable-extension/issues/370, which represents a significant performance bottleneck when running large number of orchestrations or activities.
The WorkItemDispatcher sleeps for 5 seconds whenever it notices that we've reached the maximum configured concurrency. This looping 5 second sleep effectively blocks all orchestration processing and can have a significant impact on throughput, especially when orchestrations or activities normally execute quickly.
The change is to replace the looping 5 second sleep with a `SemaphoreSlim` named `concurrencyLock` to block additional fetches until we're under our throttle limitations. With this solution, there is no sleeping, and the dispatcher will **immediately** start a new fetch as …
> Better concurrency throttling

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.Core/FilterComparisonType.cs
- src/DurableTask.Core/IOrchestrationServiceClient.cs
- src/DurableTask.Core/OrchestrationStateQuery.cs
- src/DurableTask.Core/OrchestrationStateStatusFilter.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Emulator/LocalOrchestrationService.cs
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableClient.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableConstants.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableInstanceStore.cs
- test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs
- test/DurableTask.ServiceBus.Tests/SampleScenarioTests.cs
- test/DurableTask.ServiceBus.Tests/TestHelpers.cs
Add the ability to specify which Orchestration statuses should be used during Client Side De-dupe Made Local Orchestration Service behavior consistent with Service Bus
> Add the ability to specify which Orchestration statuses should be used during Client Side De-dupe

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
- src/DurableTask.AzureStorage/Utils.cs
**Objective:** PurgeInstanceHistoryAsync now supports returning the number of instances purged, as well as the number of rows purged. Without this information, users have no way of telling whether or not their query was successful, let alone metrics about it, without querying again or manually checking the DurableFunctionsHubHistory table themselves.
- Adds new dependency on System.ValueTuple in order to return more than one value from an async task.
- Only implemented in the case where users pass a time range and list of statuses to filter by. I could add a rowsDeleted output for the PurgeInstanceHistory that only takes an instance ID.
> Add return value(s) to purge history

- Test/DurableTask.AzureStorage.Tests/AsyncAutoResetEventTests.cs
- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- Test/DurableTask.AzureStorage.Tests/TestHelpers.cs
- Test/DurableTask.AzureStorage.Tests/TestOrchestrationClient.cs
- Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/BackoffPollingHelper.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/MessageData.cs
- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Messaging/ActivitySession.cs
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/MessageCollection.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/Session.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
- src/DurableTask.AzureStorage/Utils.cs
- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
This PR contains the following bug fixes: 
* Fix for https://github.com/Azure/azure-functions-durable-extension/issues/462: Excessive polling of storage queues
* Fix for https://github.com/Azure/azure-functions-durable-extension/issues/460: Internal message loss due to partition movement
* Fix for https://github.com/Azure/azure-functions-durable-extension/issues/502: Large exception payloads will hang orchestration instances
* Fix for https://github.com/Azure/azure-functions-durable-extension/issues/520: Instances stuck in the "Pending" state but actually completed
* Partial fix for https://github.com/Azure/azure-functions-durable-extension/issues/312: Change format of blob lease IDs
* Partial fix for https://github.com/Azure/azure-functions-durable-extension/issues/338: Internal poison …
> DurableTask.AzureStorage significant performance and reliability fixes

- src/DurableTask.Core/OrchestrationContext.cs
I could set them to internal protected to expose them to implementation of the abstract class, or I could make them both virtual.
It felt like `internal protected` is less intrusive, but I admit I do not fully understand why these two are not virtual.
#236
> Make OrchestrationInstance and IsReplaying internal protected

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/Session.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/Messaging/WorkItemQueue.cs
- src/DurableTask.AzureStorage/Utils.cs
Resolves #241 
The fix is to do a more thorough search through the orchestration history to see if a particular response message matches a known request message. The previous "out-of-order" detection made some bad assumptions about the order of history events (premature optimization...), causing false-positives.
There is potentially a CPU performance impact for orchestrations that do huge fan-outs since we may end up searching through a larger portion of the orchestration history. This is acceptable, though, since it's not expected to be common and reliability is a priority.
> DurableTask.AzureStorage: Fix out-of-order regression in 1.4.0

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/StorageAccountDetails.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
#243 
- Adding a new constructor for AzureStorageOrchestrationService to accept StorageCredentials. This will help support Managed Service Identity for DurableTask.AzureStorage ([https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-vm-windows-access-storage#get-an-access-token-and-use-it-to-call-azure-storage]) 
- Currently Azure Storage does not accept TokenProvider authentication for TableClient. But I tested this by using account name and key to create Storage Credentials.
- No unit test updates yet as I was unable to use StorageCredentials (account name and key) to access Storage Emulator as I couldn't find a place to provide the blob, queue and table endpoints (to point them to the localhost emulator endpoint). Any help/suggestions …
> Accept StorageCredentials to create AzureStorageOrchestrationService

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
- src/DurableTask.Core/Command/OrchestrationCompleteOrchestratorAction.cs
- src/DurableTask.Core/EventHandlingOnContinueAsNew.cs
- src/DurableTask.Core/IOrchestrationService.cs
- src/DurableTask.Core/Settings/TaskOrchestrationDispatcherSettings.cs
- src/DurableTask.Core/TaskOrchestrationContext.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationExecutor.cs
- src/DurableTask.Emulator/LocalOrchestrationService.cs
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
- test/DurableTask.ServiceBus.Tests/ServiceBusOrchestrationServiceTests.cs
- test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
This PR aims to optimize ContinueAsNew so that an orchestration continues in memory in the dispatcher if it can instead of enqueueing a new task message.
With this Events Raised After a continueAsNew has been executed will also be collected and carried over to the next iteration of the orchestration. This a feature that can be opted out of by specifying SkipEventsOnContinuation as true in the OrchestrationService.
> Optimize Continue As New And Solve Missed Raised Events

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/BackoffPollingHelper.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
Makes the maximum queue polling interval configurable. Previously this was hardcoded to 30 seconds, which could be too long or too fast, depending on who you ask.
First step to resolving https://github.com/Azure/azure-functions-durable-extension/issues/618.
> DurableTask.AzureStorage: Make max queue polling interval configurable

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
- test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs
- test/DurableTask.ServiceBus.Tests/InstanceStoreQueryTests.cs
- test/DurableTask.ServiceBus.Tests/TaskHubClientTests.cs
- test/DurableTask.ServiceBus.Tests/app.config
Fixes https://github.com/Azure/durabletask/issues/259 by avoiding an assert fired in the `newOrchestrationRuntimeState.OrchestrationStatus` property when `ExecutionStartedEvent` is `null`.
Some tests had their timeouts increased to make them more reliable on the slower hardware.
I also disabled 5 tests which I was not able to make pass. The failing tests are tracked here: https://github.com/Azure/durabletask/issues/262
> Enable Service Bus and Emulator tests to run in Azure DevOps pipeline

- src/DurableTask.AzureStorage/StorageAccountDetails.cs
This PR makes it easier to configure the tracking store with a connection string.
@TsuyoshiUshio could you take a look? This is actually similar to what you tried originally. I thought maybe we shouldn't do this, but when I tried to use it in azure-functions-durable-extension, it was tricky and I realized trying to turn a connection string into a `StorageAccountDetails` object could be error prone in some cases. For that reason, I decided to add back the ability to configure with connection strings directly.
> Allow connection string for configuring StorageAccountDetails

- tools/DurableTask.props
This is required to unbreak the official build, which doesn't seem to like the newer `<PackageLicenseExpression>` element.
> Reverting package license change

- src/DurableTask.Emulator/LocalOrchestrationService.cs
- test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs
This Fixes Failing 
MockRecreateOrchestration Test:
This was failing as the emulator was not clearing its session state for a non-running orchestration similar tot he way it was being done in the service bus service.
MockGenerationTest:
This was failing as the Continue as the new state of a previous generation was not being saved to the instance store along with the new started ContinueAsNew state.
This fixes #255
> Fix failing tests on the DurableTask.Emulator, fixing https://github.com/Azure/durabletask/issues/255

- Test/DurableTask.AzureStorage.Tests/AutoStartOrchestrationCreator.cs
- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
This implements the auto-start feature needed for the durable actors project, for the AzureStorageOrchestrationService.
To avoid headaches with versioning, I made no changes to DurableTask.Core. Instead, this is just a semantic (functional) change to how the AzureStorageOrchestrationService back end deals with events delivered to  non-existing instances.
The new behavior is: when trying to deliver an event to a not-already-existing instance, instead of just throwing an error, first check if the instance id starts with the special character "@" . If so, insert an ExecutionStartedEvent for that instance, using an orchestration name equal to the instance id.
This could break existing code for users that are using their own instance ids and those instance ids start with '@', which is unlikely …
> Implement auto-start support in AzureStorageOrchestrationService

- src/DurableTask.Emulator/LocalOrchestrationService.cs
The Durable Functions tests have some assertions around the field LastUpdatedTime. When this field isn't set, the default values cause those assertions to fail when using DurableTask.Emulator as a storage provider.
> Use LastUpdatedTime in DurableTask.Emulator

- README.md
Documentation in README file does mention only about Service Bus Connection string for unit tests. It would be good if Azure Storage configuration for unit tests is briefly described.
This pull request adds details about Azure Storage connection string configuration for unit tests.
> Update documentation to add details about Azure storage connection string for unit tests

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
This fix is required for https://github.com/Azure/azure-functions-durable-extension/issues/688
> DurableTask.AzureStorage: Stop throwing ArgNullException on invalid status

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/MessageManager.cs
When using `AzureStorageOrchestrationService`, large status fields (input or output) are compressed and stored in blobs, which is difficult for clients to access (see issue #274).
This PR solves this problem by adding a public method for decompressing and downloading the content of such blobs.
> Provide method for downloading blobs in AzureStorageOrchestrationService

- src/DurableTask.Core/History/ContinueAsNewEvent.cs
- src/DurableTask.Core/History/EventRaisedEvent.cs
- src/DurableTask.Core/History/EventSentEvent.cs
- src/DurableTask.Core/History/OrchestratorCompletedEvent.cs
- src/DurableTask.Core/History/OrchestratorStartedEvent.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- tools/DurableTask.props
Many history event types in **DurableTask.Core** were already public, but a few were not. This PR makes all of them public. This is needed for some new feature work in Durable Functions.
This PR also contains a very minor change to avoid null-reference exceptions when middleware hijacks the orchestration execution code path.
> DurableTask.Core: Make all history event types public

- src/DurableTask.Core/OrchestrationRuntimeState.cs
This should at least partially mitigate [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/724) for Durable Functions.
> Prevent executing new events if their task has already completed

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
This PR fixes the query creation in `AzureTableTrackingStore.RewindHistoryAsync`. As far as I see there was a missing whitespace in there.
A note for the reviewer: I found not that much tests for AzureTableTrackingStore (only a few with a mocked `Instance` table) so maybe these are tested in some other way as well.
> AzureTableTrackingStore fix for RewindHistoryAsync query

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/Session.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.Core/IOrchestrationSession.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
This is a fix for the bug described in #285.
- Added a test to repro the problem.
- Added code to update the Orchestration session after a continue as new changes the runtime state.
- Added code to handle the case where messages are dequeued for an already existing session.
> Fix bug in fast continueAsNew for DurableTask.AzureStorage (#285)

- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
Adds progressively longer visibility delays for abandoned messages to
give history table time to populate.
> Fix pending orchestration race condition in Azure Storage Provider

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.Core/FrameworkConstants.cs
- src/DurableTask.Core/OrchestrationTags.cs
- src/DurableTask.Core/TaskOrchestrationContext.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.ServiceBus.Tests/SampleScenarioTests.cs
- test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
Implementation of a feature that allows sub-orchestrations to be launched as "fire-and-forget". For any such sub-orchestration, the parent orchestration continues immediately and does not wait for the result of the sub-orchestration.
We need this feature for allowing entities in DF to start new orchestrations (azure/azure-functions-durable-extension#715).
To keep this a non-breaking change to the API, and to avoid changing any serialized data formats, I used the existing `tags` data structure to indicate that an orchestration is fire-and-forget. So, one can simply set the `FrameworkConstants.FireAndForgetOrchestrationTag` in `tags`, when creating a sub-orchestration, and this then makes the sub-orchestration fire-and-forget. 
One somewhat subtle point is that I have to specifically remove …
> Add support for fire-and-forget suborchestrations

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Redis/DurableTask.Redis.csproj
The latest DurableTask.Core (v2.1.3) package introduced breaking changes, making it incompatible with existing versions of DurableTask.AzureStorage and DurableTask.Redis. Need to update these packages to target the latest version of DurableTask.Core.
Durable Functions also needs this updated DurableTask.AzureStorage package because it enables us to use the new "fire-and-forget" support for sub-orchestrations.
> Increment versions of AzureStorage and Redis nuget packages

- src/DurableTask.AzureStorage/MessageManager.cs
We previously generated "unique" blob names using the SequenceNumber
field of the MessageData object. However, these sequence numbers are
generated by the client, This means is no uniqueness guarantee for a given
instance id, as any VM running the application is allowed to send
messages. This meant it was possible for large messages sent from
different VMs to the same instance could overwrite each other.
We now use activity ids, as they are random guids that should
not conflict with other messages, regardless of which client they are
sent from.
> Make large message blob names unique

- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
Removed ToLower on blob storage path names that caused blobs to be stored with a lowercase instanceId.
Fixes azure-functions-durable-extension issue #755: 
https://github.com/Azure/azure-functions-durable-extension/issues/755
> Removed ToLower on blob storage path names

- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/MessageCollection.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Resolves #328 
This PR greatly simplifies the message counting logic to avoid message-piling problems when many messages are sent to an active instance. I'm keeping a list of all message IDs that we read from the queue and removing from that list when we abandon or delete those messages. This solution should be much more accurate than the previous method while also fixing the pile-up problem.
> DurableTask.AzureStorage: Orchestration message counting fixes

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
A previous change upgraded the Azure Storage SDK from 8.6 to 9.3.3. This
changes the version to 9.3.1, as 9.3.3 broke compatibility between the Durable
Functions extension and the Azure Storage extension. This PR also adds a
comment next to the dependency in the csproj to warn against changing
this in the future.
> Change Azure Storage SDK back to previous version

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
Allowed configuration to throw an exception when attempting to create an orchestration instance in an existing dedupe status.
Related to this issue in azure-functions-durable-extension
https://github.com/Azure/azure-functions-durable-extension/issues/367
> Configuration to throw an exception when an orchestration is in an existing dedupe state

- Test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
- src/DurableTask.AzureStorage/Monitoring/PerformanceHeartbeat.cs
This is an initial draft of the changes needed for runtime scale in the durable extension. I haven't made any tests yet, just looking for initial feedback.
> Refactoring monitor to allow for metrics collection and ad hoc scale decisions.

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Dependency for Durable Functions v2.0.0 and v1.8.4 releases.
> Increment DurableTask.AzureStorage to v1.6.5

- src/DurableTask.Core/Common/DateTimeUtils.cs
Resolves https://github.com/Azure/durabletask/issues/319. 
In .net core 3.0, validation was added so readonly fields could not be set with reflection.
> Removed invalid .net core 3 reflection call.

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.Core/IOrchestrationSession.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
Fixes two bugs in how timers are handled. These fixes are necessary for implementing the entity reminder feature azure/azure-functions-durable-extension#716.
- the `DeferredMessages` mechanism introduced in #331 was not functioning correctly with extended sessions, as the deferred messages, even if ready to deliver, would just sit in the session until the session times out. I updated the code in `CompleteTaskOrchestrationWorkItemAsync` so that it redelivers deferred messages whenever the execution id of the session changed.
- I limited the autostart mechanism so it applies only to events. Otherwise, a timer message to a not-yet-existing execution of an entity can autostart a new one, causing unnecessary and harmful conflicts. This bug was already fixed in #327 but the latter PR is …
> fixes for handling timers and extended sessions

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.Core/Exceptions/SessionAbortedException.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
This PR adds support for delayed entity messages, by recognizing a specially encoded delay parameter in event names, and setting the visibility timeout. This affects only entity messages, and does not require changes to core, only to the Azure table storage provider.
This PR also improves split brain handling in two cases:
- detects conflict on concurrent creation of an instance
- terminates extended session when conflict is detected
The latter required changing `DurableTask.Core` because the exception that terminates the extended session needs to be caught, so the work item scheduler does not back off.
> Support for delayed entity messages and improved split brain handling

- Test/DurableTask.AzureStorage.Tests/OrchestrationInstanceStatusQueryConditionTest.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
Added InstanceIdPrefix to allow query of an instance only given the first part of the instanceId. For example, with Entities, this allows query of EntityName (where instance id is composed of EntityName and EntityKey).
Related to issue https://github.com/Azure/azure-functions-durable-extension/issues/997
In the azure-functions-durable-extension repository.
> Added InstanceIdPrefix to OrchestrationInstanceStatusQueryCondition

- src/DurableTask.Core/TaskHubClient.cs
- tools/DurableTask.props
Added second constructor to TaskHubClient to allow for a custom JsonDataConverter to allow for custom serialization settings.
Related to this issue in the azure-functions-durable-extension repository:
https://github.com/Azure/azure-functions-durable-extension/issues/65
> Added constructor to TaskHubClient with JsonDataConverter input

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStatus.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/1020.
We were already handling the race condition for setting the "Pending" status on a new instance.  However, we did not correctly handle the case where we were replacing an existing instance with a "Pending". This resulted in cases where orchestration instances completed successfully but had a "Pending" status in the instances table.
This fix handles the latter race condition (replacing an existing instance). After this, both cases should be handled, and we should never have a completed instance in the "Pending" status.
> Fix instance status update race condition (for replace)

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
Added FetchInput property to allow to specify if the Input column should be selected in the query created with OrchestrationInstanceStatusQueryCondition.
Related to https://github.com/Azure/azure-functions-durable-extension/issues/997
to allow query of entities without selecting the input column.
> Added FetchInput property to OrchestrationInstanceStatusQueryCondition

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Redis/DurableTask.Redis.csproj
For our upcoming release of Durable Functions 2.1, we need to release
DurableTask.Core, DurableTask.Emulator, DurableTask.AzureStorage, and
DurableTask.Redis. DurableTask.Core and DurableTask.Emulator already had
their version incremented, so this PR increments the version for the
other packages.
> Update DurableTask.AzureStorage and DurableTask.Redis package versions

- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
- tools/DurableTask.props
The license change broke the official build in Azure DevOps - reverting
Also reverting the icon change to avoid potential issues
Sneaking in one additional fix for DurableTask.AzureStorage instance queries
> Fixes to unblock official build

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/Exceptions/SessionAbortedException.cs
- src/DurableTask.Core/TaskActivity.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestration.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationExecutor.cs
- tools/DurableTask.props
This is a followup item to help fix https://github.com/Azure/azure-functions-durable-extension/issues/472 but it also directly applies to https://github.com/Azure/azure-functions-durable-extension/issues/1133.
The idea is to take the existing `SessionAbortedException` (added by Sebastian) and make it work for abandoning in-flight orchestrations and activities. Basically, if an orchestration or activity function throws this exception, the dispatcher will abandon the work item rather than failing the activity/orchestration. The work item can then be picked up by a healthy instance and immediately resumed.
The primary purpose of this feature is to enable correctly handling host shutdown scenarios. For example, in Durable Functions, when the Functions host shuts down in the middle of an …
> Support for aborting orchestration and activity executions

- Test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
- Test/DurableTask.AzureStorage.Tests/TestHelpers.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/382.
This is a small update to the orchestration work item polling logic in DurableTask.AzureStorage that proactively abandons messages if we've lost the lease for the source queue since fetching. The intent is to mitigate some of the split-brain problems see when partitions move around.
It won't fix 100% of split-brains caused by partition movement, but it should take care of the low-hanging fruit.
> Azure Storage: Abandon prefetched orchestrator messages if the lease is lost

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
It is possible for the history table to get into a state where the
latest execution history is first, followed by the previous execution
history, with the last entry for an instance id being the sentinal row.
The previous history parsing logic stopped processing as soon as it saw
a new execution id, meaning it failed to grab the ETag from the sentinal
row.
This, in combination with changes made when the ETag were not present,
caused UpdateState calls to fail, meaning queue messages for Activities
were being scheduled without recording that we did schedule them. This
leads to duplicate Activity executions until we retrieve the history
with an execution id (i.e. after an activity function successfully
executes).
This fix makes our ETag retrieval logic more robust.
> Fix ETag retrieval for orchestrations with multiple executions

- Test/DurableTask.AzureStorage.Tests/Correlation/CorrelationScenarioTest.cs
- Test/DurableTask.AzureStorage.Tests/Correlation/DurableTaskCorrelationTelemetryInitializer.cs
- Test/DurableTask.AzureStorage.Tests/Correlation/TelemetryActivator.cs
- Test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
- Test/DurableTask.Core.Tests/W3CTraceContextTest.cs
- samples/Correlation.Samples/Correlation.Samples.csproj
- samples/Correlation.Samples/DurableTaskCorrelationTelemetryInitializer.cs
- samples/Correlation.Samples/Properties/launchSettings.json
- samples/Correlation.Samples/ScenarioInvoker.cs
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/HttpCorrelationProtocolTraceContext.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Core/TraceContextFactory.cs
- src/DurableTask.Core/W3CTraceContext.cs
Hi @cgillum 
I update the System.Diagnostics.Source to 4.6.0 
The reason for this update is: 
* WebJobsHost SDK update the DiagnosticSource to 4.6.0 (See this commit: https://github.com/Azure/azure-webjobs-sdk/commit/5f1f62fa12979846346689e940efc37bb55f113f#diff-71ab67b70c446b3e5c0665fa1e119f0e) 
* We can remove the dependency of Application Insights from the DurableTask.Core
* Fix the problem of W3C tracing on Durable Functions. The 4.6.0 will cause breaking changes in the Activity interface. 
* Portal behavior change of W3C tracing.
For more details about breaking change, you can refer to this blog post. 
https://medium.com/@tsuyoshiushio/system-diagnostics-activity-update-and-distributed-tracing-in-c-f02428dcd050
> Update System.DiagnosticSource for enabling W3C on Durable Functions

- Test/DurableTask.AzureStorage.Tests/Correlation/CorrelationScenarioTest.cs
- samples/Correlation.Samples/docs/overview.md
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationWorkItem.cs
I found that current implementation doesn't work well for extended session settings. 
This PR unlock the extended session with Distributed Tracing. 
Could you have a look, @cgillum ?
> Enabling Extended Session Distributed Tracing

- samples/Correlation.Samples/docs/overview.md
There was a missing link on the Correlation Documentation.
> Document fix: missing link for the correlation branch 

- Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
Previously, when there is a null continuation token in the paginated
GetInstances API call for DurableTask.AzureStorage, we return the base64
encoded value of "null", instead of null.
We now return null properly in this case.
> Handle null continuation tokens properly in paginated GetInstances API

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/TaskOrchestrationContext.cs
- src/DurableTask.Redis/DurableTask.Redis.csproj
- tools/DurableTask.props
Reverting this to the default serializer to fix a bug where the exception would not retain the message/input of the function.
> Reverted TaskOrchestrationContext HandleTaskFailedEvent Serializer

- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Monitoring/AzureStorageOrchestrationServiceStats.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Currently, when a host lease is lost and reclaimed before its pending messages are processed, a new control queue is spun up, losing track of what messages it has already processed.
This PR keeps track of pending messages in the shared AzureStorageOrchestrationServiceStats class, so that even when a new control queue is spun up, the pending messages from a previous iteration are still available.
> Prevent value drift on PendingOrchestrationMessages

- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
resolves https://github.com/Azure/durabletask/issues/280
When a message is renewed right before a delete operation takes place, the delete will fail and the activity will run twice.
This retry on TaskHubQueue.DeleteMessageAsync will retry one time when CloudQueue.DeleteMessageAsync returns a 404.
> Implemented retry for DeleteMessageAsync to fix delete/renew race condition issue

- src/DurableTask.Core/TaskHubWorker.cs
- src/DurableTask.Core/WorkItemDispatcher.cs
Improves graceful shutdown the following ways:
1. Stop the dispatchers and orchestration service in parallel to save time.
2. Reduce delay from 4 seconds to 1 second when waiting for inflight work items.
3. Fix race condition where we could accidentally mark a WorkItemDispatcher as stopped when there are in flight work items.
> Improve speed of graceful shutdown, and remove race condition

- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/Remote/RemoteOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Service/ActivityLoggingMessageHandler.cs
- src/DurableTask.AzureServiceFabric/Service/Startup.cs
1. Logging response code and reponse content details when Create Orchestration Failed
2. Register ActivityLoggingMessageHandler as logging provider and provide full uri & reponse code & details
3. Bump up version
> Hotfix for DTFX logging issue

- src/DurableTask.Core/OrchestrationRuntimeState.cs
- src/DurableTask.Core/OrchestrationRuntimeStateDump.cs
The actions of dumping the orchestration state for the telemetry event
type TaskOrchestrationDispatcher-ExecuteUserOrchestration-Begin is
expensive. It scales linearly with the number of events, meaning
orchestrations with large histories start to spend most of their time
writing this verbose telemetry item, which is not ideal.
Instead, we now just log the number of events, as this is a constant
time operation.
> Improve performance of the runtime state dump

- src/DurableTask.Core/History/HistoryEvent.cs
Small change required for a DurableTask.SqlServer prototype that I'm working on.
The intent is to allow providers to load history events from storage without necessarily using serialization.
> Make HistoryEvent's IsPlayed and Timestamp properties settable

- src/DurableTask.ServiceBus/Common/Abstraction/ServiceBusAbstraction.cs
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
- test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.csproj
Issue: DurableTask.ServiceBus prevents using the latest `Microsoft.IdentityModel.Clients.ActiveDirectory` package as it causes a dependency on < 5.0.0 due to its usage of `Microsoft.Azure.ServiceBus, 3.3.0` in netstandard. Updating this package removes this conflict.
The only significant change in this update is the deprecation of a constructor, which I added a new one for and marked the current one `[Obsolete]`
> Update Microsoft.Azure.ServiceBus to 4.1.3

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- tools/DurableTask.props
* DurableTask.AzureStorage 1.7.6 -> 1.7.7
* DurableTask.Core 2.2.5 -> 2.3.0
* DurableTask.Emulator 2.2.5 -> 2.3.0
* DurableTask.ServiceBus 2.2.5 -> 2.3.0
DurableTask.Core and friends is a minor version upgrade because of the public API change.
> Incrementing nuget package versions for release

- test/DurableTask.SqlServer.Tests/DurableTask.SqlServer.Tests.csproj
Tests were written in netcore2.2, which is EOL, so it is no longer
supported by the latest version of the .NET SDK used in the CI pipeline.
We have to downgrading to 2.1, as 3.1 is not supported on our VS2017 agents.
> Downgrade DurableTask.SqlServer.Tests to netcore2.1

- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Messaging/WorkItemQueue.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs
- test/DurableTask.ServiceBus.Tests/ErrorHandlingTests.cs
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/1377.
Based on my investigation, the only reasonable explanation for the stuck orchestration that I can think of is that this is a storage SDK deadlock when checkpointing orchestration history. I'm adding deadlock protection for this code path in **AzureStorageTrackingStore.cs**.
I also made a very small logging fix in **MessageManager.cs** related to large messages that I discovered while investigating the issue.
> Storage SDK deadlock protection for UploadHistoryBatch

- src/DurableTask.AzureStorage/MessageManager.cs
This change resolves [issue #1406](https://github.com/Azure/azure-functions-durable-extension/issues/1406) from the azure-function-durable-extension repo.
The current implementation to download contents from a blob (`OpenReadAsync()`) has a chance to result in a race condition, but switching to using the `DownloadToStreamAsync(Stream)` API would solve this issue.
> Use DownloadToStreamAsync(Stream) to download blob contents

- src/DurableTask.ServiceFabric/FabricOrchestrationServiceClient.cs
This is change is specific to V1 implementation of Service Fabric provider. We needed to terminate orchestration from the store if the graceful cleanup fails.
> [ServiceFabric-V1] Enable an option to cleanup the orchestration from the store

- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Logging/NoOpLoggerFactory.cs
- src/DurableTask.Core/DurableTask.Core.csproj
Two fixes:
* There were inconsistencies in my `Microsoft.Extensions.Logging.Abstractions` dependencies across projects. This was resulting in runtime failures in `WebJobs.Extensions.DurableTask` when using Functions V1 bits. I've updated these dependencies to make things consistent.
* I accidentally switched on `<GeneratePackageOnBuild>` in a previous PR. Turning it back off in this one.
I also tested this on Functions v1 host (net461) and verified that things seem to be working correctly (required a lot of `MethodNotFound` error debugging due to compatible assembly version issues).
> Make logging dependencies consistent

- src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/OrchestrationInstanceStatus.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.Core/History/ExecutionStartedEvent.cs
- src/DurableTask.Core/OrchestrationState.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Redis/RedisOrchestrationService.cs
- src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationStateEntity.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/FunctionalTests.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- test/DurableTask.Redis.Tests/EndToEndServiceScenarioTests.cs
- test/DurableTask.ServiceBus.Tests/SampleScenarioTests.cs
I would like to start conversation about adding scheduled start to durable functions. One of the possible ways to achieve the same behavior today is by creating a timer activity at the orchestration function start, as illustrated below:
```c#
[FunctionName("OrchestrationStart")]
public static Task OrchestrationStart(
[OrchestrationClient] DurableOrchestrationClient starter)
{
// Orchestration input comes from the queue message content.
return starter.StartNewAsync("Orchestration", "input-for-the-orchestration");
}
[FunctionName("Orchestration")]
public static async Task<bool> Orchestration(
[OrchestrationTrigger] DurableOrchestrationContext context)
{
await context.CreateTimer(context.CurrentUtcDateTime.Add(TimeSpan.FromDays(1)));
// real activities will start here
}
```
The PR contains …
> Add possibility of scheduling an orchestration start

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
@amdeel noticed that my previous logging PR broke compatibility with Azure Functions 2.0 host (I tested against 1.0 and 3.0, but not 2.0). This PR resolves the issue and should be compatible with all three supported versions of the Functions runtime.
The problem was with the `Microsoft.Extensions.Logging.Abastractions` dependency for `netstandard2.0`. The `3.x` builds of this package are not compatible with the Functions 2.0 host, which runs on .NET Core 2.2. Reducing the dependency to `2.2.0` (to match the version used by Functions/WebJobs) seems to have resolved the issue based on my local testing.
> Reverting logging dependencies to 2.2.0

- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
This change accounts for the fact that the Azure Storage SDK encodes the
content of the queue message in base64 encoding, increasing the size by
~33%. We shrink our message size maximum accordingly.
> Reduce maximum queue message size from 60 KB to 45 KB

- src/DurableTask.Core/Serializing/JsonDataConverter.cs
This change prevents strings that look like dates from being serialized into DateTime objects.
related to https://github.com/Azure/azure-functions-durable-js/issues/208
> Updated JsonConverter default JsonSerializerSetting to include DateParseHandling.None

- tools/DurableTask.props
In preparation for the "official" August 2020 release, which will be used by Durable Functions.
We unexpectedly had to do an early release of DurableTask.Core v2.4.0 (for the GA of DurableTask.AzureServiceFabric) which did not have the full payload of changes we wanted, hence why we have to do another version bump.
> Increment DurableTask.Core to v2.4.1

- src/DurableTask.AzureStorage/Partitioning/AppLeaseManager.cs
- test/DurableTask.AzureStorage.Tests/TestOrchestrationClient.cs
Some tests were failing due to trying to delete an app lease when
someone else owns the lease.
> Make AppLease deletion safer

- src/DurableTask.AzureStorage/Partitioning/AppLeaseManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
PR #435 attempted to fix large message inconsistencies in how it handled UTF8 vs UTF16 character counts, but it turns out that the code path that starts new orchestrations relied on the overcounting of characters that used to occur.
This PR fixes that case, and adds more testing with characters of varying UTF8 and UTF16 sizes to make sure we cover all of the edge cases.
Addresses #448
> Make large message handling more robust

- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
Adds a small fix to new partition management strategy, and makes it the default for DurableTask.AzureStorage.
> Make partition management strategy default

- src/DurableTask.AzureServiceFabric/FabricOrchestrationService.cs
- src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Remote/DefaultStringPartitionHashing.cs
- src/DurableTask.AzureServiceFabric/Remote/FabricPartitionEndpointResolver.cs
- src/DurableTask.AzureServiceFabric/Remote/IPartitionHashing.cs
- src/DurableTask.AzureServiceFabric/Remote/RemoteOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Service/ActivityLoggingMessageHandler.cs
- src/DurableTask.AzureServiceFabric/Service/FabricOrchestrationServiceController.cs
- src/DurableTask.AzureServiceFabric/Stores/SessionProvider.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/AssemblySetup.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/FunctionalTests.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/StressTests.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/Utilities.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/WaitForOrchestrationTests.cs
- test/DurableTask.Test.Orchestrations/Performance/ExecutionCountingActivity.cs
- test/TestFabricApplication/TestApplication.Common/Orchestrations/RecurringOrchestration.cs
- test/TestFabricApplication/TestApplication.Common/Orchestrations/RecurringOrchestrationInput.cs
- test/TestFabricApplication/TestApplication.Common/Orchestrations/RecurringTargetOrchestration.cs
- test/TestFabricApplication/TestApplication.StatefulService/TestOrchestrationsProvider.cs
1. Fixed the race condition in SF provider
2. Fixed IsMaxMessageCountExceeded to enable more parallel processing
3. Fixed RemoteTaskHubClient to handle exceptions properly
4. Fixed multiple flaky tests
5. Locate the Service Fabric test application using relative path
> [ServiceFabricProvider]: Fix a race condition while adding or updating the lockedSessions dictionary and other changes

- src/DurableTask.ServiceFabric/SessionsProvider.cs
Orchestration Dispatcher is trying to Release the session (UnlockSession) while the Activity Dispatcher is trying to complete the activity (EnqueueSession). In the Service Fabric provider layer, we use a concurrent dictionary for session locks. EnqueueSession and UnlockSession actions tried to update the SessionLocks dictionary in non-atomic way which left the session in a state where it can't be made available for further processing.
> [ServiceFabricProvider]: Fix a race condition while adding or updating the lockedSessions dictionary

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.Core/CorrelationTraceClient.cs
- src/DurableTask.Core/History/ExecutionStartedEvent.cs
- src/DurableTask.Core/History/HistoryEvent.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.AzureStorage.Tests/Correlation/CorrelationScenarioTest.cs
- test/DurableTask.AzureStorage.Tests/TestOrchestrationClient.cs
Hi @cgillum 
I found the root cause why the correlation test fails. 
`TaskHubClient` changes the behavior. `CorrelationTraceClient.Propagate(() => CreateAndTrackDependencyTelemetry(requestTraceContext));` Should be coming before a method that eventually call the `TaskHubQueue`.  
This is the old code.  
https://github.com/TsuyoshiUshio/durabletask/blob/correlation/final/src/DurableTask.Core/TaskHubClient.cs#L497-L501
Only the External Event with non-extended session will fail. I'm not fully understand the new behavior, however, it is getting very close.
> Fix:  correlation test fail except for external event with extended session

- src/DurableTask.Core/Serializing/JsonDataConverter.cs
- tools/DurableTask.props
I noticed this issue when working on the DurableTask.SqlServer backend provider. I think it should be a non-breaking change that only impacts that value written to the backend storage provider. I don't think this impacts null handling in user code. in that sense, it is primarily a storage and potentially a slight performance optimization.
I also incremented the version number of DurableTask.Core in this PR.
> Preserve null values when serializing to storage

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
Changed query used when starting an orchestrator to search the instances table for an existing orchestrator instance to prevent undesirable 404s.
Changed the query from a row retrieval operation to a query for existing instance statuses on the specific instance Id. When existing statuses associated with the instance Id are returned, the original row retrieval operation will take place in order to get the ETag associated with the row.
This change will add one additional storage transaction to starting a new instance only when attempting to start an instance with an existing instance Id. This change will prevent undesirable 404s in customers' App Insights dependency table.
resolves https://github.com/Azure/azure-functions-durable-extension/issues/593
> Changed query used when starting orchestration to prevent 404s

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.Core/Common/Entities.cs
- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/History/HistoryEvent.cs
- src/DurableTask.Core/OrchestrationRuntimeState.cs
- src/DurableTask.Core/OrchestrationState.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Emulator/DurableTask.Emulator.csproj
- src/DurableTask.Redis/DurableTask.Redis.csproj
This contains the new Netherite backend implementation, with the Faster storage provider and the EventHubs transport provider. In this first version autoscaling is not yet supported, but it does support manual scaling (it balances the partitions among all the started nodes).
Most of this PR adds new files and projects; There are two new projects, DurableTask.EventSourced and DurableTask.EventSourced.Tests.
There are also some small changes / fixes to existing files:
- suppress deprecation warnings when building NuGet packages
- move entity-related functionality from AzureStorage to DurableTask.Core.Common so it can be shared by the providers
- make the `ExecutionCompletedEvent` field of `OrchestrationRuntimeState` public
- add a method to `OrchestrationState` that allows cloning of the …
> Allow Netherite back-end to be implemented externally

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/ILeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/LegacyPartitionManager.cs
- src/DurableTask.AzureStorage/Partitioning/SafePartitionManager.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
The Azure Functions scaling infrastructure relies on the partitionCount
value in the taskhub.json. However, our logic to create this
taskhub.json only updated the blob if it did not exist. This means that
if the taskhub lease store was created with one value of partitionCount,
and the customer updated the partitionCount, the taskhub.json would not
be updated, and the scaling logic would continue to look only at the
original control queues.
This PR aims to update the taskhub.json partition count if it is out of
sync with the provided value in AzureStorageOrchestrationService, so
that customers don't need to update this value by hand to get correct
scaling behavior.
> Update stale taskhub.json in DurableTask.AzureStorage

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Redis/DurableTask.Redis.csproj
- tools/DurableTask.props
Incrementing the following versions:
- DurableTask.AzureStorage v1.8.1 -> v1.8.2
- DurableTask.Core/DurableTask.Emulator v2.4.2 -> v2.5.0
- DurableTask.Redis v0.1.5-alpha -> v0.1.6-alpha
> Increment various package versions for Durable Functions v2.4.0 release

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
Implement a temporary mitigation for `null` custom status updates not
actually updating the state in Azure Table Storage due to the way that
merge operations happen.
A better long term mitigation is detailed at
https://github.com/Azure/durabletask/issues/477.
> Mitigate null custom status regression in DurableTask.AzureStorage

- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Drop message when the current generation instance hasn't started.
> Add started event null check, Fix#457

- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
Currently, there's a race condition where raising an event to a pending orchestrator can lead to a raiseEvent message being processed before an executionStarted one. This leads to the workItem batch being discarded and the orchestrator getting into a bad state.
This _draft_ PR adds a pre-processing step that re-orders the workItem messages when an ExecutionStarted event is not at the beginning of its `NewMessages` property. We do the re-ordering in-place, for performance.
If we believe the in-place re-ordering is a premature optimization, we can replace the re-ordering method with two lines: one calling the IList `insert` API, and the other calling the IList `delete` API.
> Enforce that ExecutionStarted is the first event in a WorkItem

- src/DurableTask.Core/Logging/StructuredEventSource.cs
- src/DurableTask.Core/Serializing/DataConverter.cs
- tools/DurableTask.props
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/1613.
The problem is that we're trying to cast a `null` value into `T`, which is only legal if `T` is a reference type. If it is a value type, like `int` or `Guid` then the cast fails with a `NullReferenceException`. I found this by testing Durable Entities using the SQL backend.
Also included in this PR is a small fix to our logging to handle a certain scenario where we might unintentionally log a null value.
I've also proactively incremented the version of DurableTask.Core in this PR to **2.5.1**.
> Fix a null-ref in the core deserialization path

- src/DurableTask.AzureStorage/MessageData.cs
Fix for #491 
Overall, AzureStorage owners should re-evaluate their use of `TypeNameHandling.Object` while serializing here, as it makes the whole system very fragile to type renames and namespace changes. My suggestion is to use `TypeNameHandling.None` and to implement `IExtensibleDataObject` on `MessageData` to give this the ability to round trip between difference versions of DurableTask.AzureStorage and not lose any data.
This change should not break existing orchestrations, Newtonsoft.Json can handle mismatch between `$type` property and `TypeNameHandling` setting.
> TypeNameHandling.None on MessageData.Sender

- src/DurableTask.Core/ReflectionBasedTaskActivity.cs
Small PR to make this property have a public setter, but also enforce non-null values. The justification is that it may be useful to override this value in the dispatcher middleware with a custom converter - for example our system has a DI-enabled converter.
> Public ReflectionBasedTaskActivity.DataConverter setter

- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/KeySanitation.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/KeySanitationTests.cs
Uses a mechanims for escaping/unescaping characters that are invalid for use in partition keys on Azure Tables.
> sanitize the instance ids used as partition keys

- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
This PR keeps `instanceState` consistent with `runtimeState` in case `instanceState` has not been initialized before use in `OnProcessWorkItemAsync`.
Previously, this caused a nullPtr exception that would prevent orchestrators from checkpointing their progress, therefore getting stuck.
> Remove possible nullPtr exception in OnProcessWorkItemAsync

- src/DurableTask.Core/DurableTask.Core.csproj
The Distributed Tracing work required adding System.Reactive.Core as a
dependency. However, if the customer app was using a different major
version of System.Reactive, it could lead to ambiguous compilation
issues.
Adding this package (and upgrading to use v4 of System.Reactive.Core)
should resolve this issue.
Addresses https://github.com/Azure/azure-functions-durable-extension/issues/1620
> Add System.Reactive.Compatibility as a dependency to DurableTask.Core 

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Logging/LogEvents.cs
- src/DurableTask.AzureStorage/Logging/LogHelper.cs
A null value for OrchestrationInstance on the runtimeState object in
AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync
causes rare null reference exceptions for some customers. Unfortunately,
due to the lack of helpful information when this exception is
encountered, we don't know what scenarios cause the orchestration
instance to be null.
This PR currently just adds null coalescing + a warning log. It's
possible that a null execution id that this results in will cause issues
down the line in this method, but this will at least make sure we know
which orchestration instance hit this code path, which makes it far
easier to diagnose the issue.
Attempts to address #487
> Fix null reference exception in DurableTask.AzureStorage

- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/Service/TaskHubProxyListener.cs
When utilizing Service Fabric provider in durable task, during the initialization phase of `TaskHubWorker` artifacts, there is no available API to access the corresponding `TaskHubClient`. The only available option is to create a `TaskHubClient` with the `RemoteOrchestrationServiceClient` which routes the request via HTTP. This is not ideal due to the fact that we will be routing requests to the outside of the process back into the same process again.
There is a version of orchestration client named `FabricOrchestrationServiceClient` which is capable of querying the orchestration state within the process itself by querying the underlying reliable collections. However, this client is not publicly exposed. The proposed solution creates a new `TaskHubClient` based on the …
> Service Fabric provider: Overload for orchestration registration delegate, adding a TaskHubClient for querying state

- src/DurableTask.AzureServiceFabric/Constants.cs
- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/Extensions.cs
- src/DurableTask.AzureServiceFabric/IPartitionEndpointResolver.cs
- src/DurableTask.AzureServiceFabric/Remote/FabricPartitionEndpointResolver.cs
- src/DurableTask.AzureServiceFabric/Remote/RemoteOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Service/ActivityLoggingMessageHandler.cs
- src/DurableTask.AzureServiceFabric/Service/ProxyServiceExceptionHandler.cs
- src/DurableTask.AzureServiceFabric/Service/ProxyServiceExceptionLogger.cs
- src/DurableTask.AzureServiceFabric/Tracing/TracingExtensions.cs
Service Fabric's `ServicePartitionResolver` class maintains an internal cache of `ResolvedServicePartition` objects for each partition which is served by an internal reference of `FabricClient`. The cache is refreshed via 2 different processes:
-  A notification protocol through which the `FabricClient` notifies resolver that a given value is stale and needs to be updated.
-  A complaint based resolution, as part of which, the client passes in the previously retrieved `ResolvedServicePartition` object to the `ResolveAsync()` API call. This API call notifies the resolver that the previously provided object is stale and a new one should be fetched from the `FabricClient`
Service Fabric also states in their documentation that the notification mechanism cannot be completely relied upon since …
> Service Fabric provider: Identify stale partition endpoints and force refresh SF resolver cache in such a scenario

- src/DurableTask.Emulator/LocalOrchestrationService.cs
- src/DurableTask.Emulator/PeekLockSessionQueue.cs
The emulator currently ignores the ScheduledStartTime field and executes all orchestrations immediately. This broke my tests, so I copied the emulator locally and fixed it with this change. Would like to share it back to the project for other's benefit and also to have it reviewed by the project owners for correctness.
> Add support for ScheduledStartTime in Emulator

- Test/DurableTask.AzureStorage.Tests/StressTests.cs
- Test/DurableTask.AzureStorage.Tests/TestInstance.cs
- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AsyncAutoResetEvent.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/OrchestrationInstanceStatus.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
- src/DurableTask.Core/Logging/LoggingExtensions.cs
- src/DurableTask.Core/Logging/StructuredEventSource.cs
- test/DurableTask.AzureStorage.Tests/Correlation/CorrelationScenarioTest.cs
- test/DurableTask.AzureStorage.Tests/TestHelpers.cs
- test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
- tools/DurableTask.props
The DT.AzureStorage backend has always been vulnerable to concurrent starts of orchestrations with the same instance ID. This PR finally fixes that, as well as a couple other issues found along the way.
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/1730 (this was the main issue being fixed)
Fixes https://github.com/Azure/durabletask/issues/527 (found this while working on ^)
Often time users want to start an orchestration with a specific instance ID if it's not already started. To do so, they'd write code that looks like this:
```
var existing = GetOrchestrationInstance(id)
if (existing is null or existing is stopped)
StartNewOrchestration(id)
```
The problem with this logic is that it's not thread-safe. If two threads call this logic at the same time, on the …
> DT.AzureStorage: Runtime de-dupe support for orchestration start events

- src/DurableTask.AzureServiceFabric/Extensions.cs
- src/DurableTask.Core/TaskOrchestrationContext.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/DeploymentUtil/ApplicationInfoReader.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/DeploymentUtil/DeploymentHelper.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/FunctionalTests.cs
2 changes in this PR:
1. DurableTask.AzureServiceFabric: Disabled instanceId validation to alllow any chars to let the application decide on the chars to be allowed.
2. DurableTask.Core: Fix the issue "Multiple ExecutionCompletedEvent found, potential corruption in state storage"
Multiple ExecutionCompletedEvents possible when orchestration's termination and completion happens at the same time.
> Fixes for DurableTask.AzureServiceFabric and DurableTask.Core

- Test/DurableTask.AzureStorage.Tests/TimeoutHandlerTests.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/TimeoutHandler.cs
In AzureStorage variant, if maximum number of timeouts are hit per call (5) app gets recycled. This is to bring system back into healthy state. However, this kill can result in issues with requests in flight (as `Environment.FailFast` does not perform graceful shutdown). Adding provision to allow graceful shutdown (e.g. `IHostApplicationLifetime.StopApplication` in AspNetCore).
Graceful shutdown tasks are given 35 seconds to finish (aligning with the 30 second host shutdown that .Net has).
> Adding provision to perform graceful shutdown before process kill due to max timeout hits

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
The key issue being fixed is a problem where execution started messages are executed out of order after https://github.com/Azure/durabletask/pull/528 was merged. None of the existing tests were sensitive to this. However, some of the Durable Functions tests were.
Durable Functions tests to verify:
> Fixed a message order regression caused by the de-dupe PR (#528)

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Fixes #543
We have some logic that incorrectly deletes messages when we see messages from multiple generations at the same time. The logic is both wrong and seems to be unnecessary, so this PR mostly just removes code and adjusts the comments.
A couple things I want to verify before merging:
> DT.AzureStorage: Fix message loss bug in ContinueAsNew scenarios

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLease.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/Lease.cs
- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
- src/DurableTask.AzureStorage/Partitioning/LegacyPartitionManager.cs
- src/DurableTask.AzureStorage/Partitioning/SafePartitionManager.cs
- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
- src/DurableTask.AzureStorage/Storage/Blob.cs
- src/DurableTask.AzureStorage/Storage/BlobContainer.cs
- src/DurableTask.AzureStorage/Storage/DurableTaskStorageException.cs
- src/DurableTask.AzureStorage/TimeoutHandler.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs
This PR is the first in a series of AzureStorage refactor PRs. Part of this work item: https://github.com/Azure/durabletask/issues/514
The goal of this refactor is to centralize all AzureStorage types and make storage calls in a single place. With this PR, all storage types will be contained in a new folder called "Storage." All storage request calls will go through a method in a class AzureStorageClient. Types Blob, BlobContainer, and DurableTaskStorageException were also added to wrap around related AzureStorage types.
This PR is primarily focused on changes related to Blob storage, so the main changes are to BlobLeaseManager and MessageManager, with the exception of AppLeaseManager.
> Refactor: First iteration blob storage refactor

- src/DurableTask.Core/OrchestrationRuntimeState.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
A recent change to log only the history dump instead of the history
itself resulted in a null-ref when running Release code. This is because
in release builds, the Events field on OrchestrationRuntimeStateDump is
null.
This PR fixes that by:
1. Logging the entire dump instead of just Events so we at least get the
number of Events in the instance completion events trace.
2. Including an empty list of Events and NewEvents on the dump in
Release mode so we don't run into future NRE.
> Fix null ref in instance completion trace

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
In an attempt to reduce the latency + storage transaction impact of the
new deduplication of ExecutionStarted events, we tried to query the
status of multiple instance ids in a single query. Unfortunately, for
certain scenarios, this resulted in very large latency requests.
In order to reduce latency, we will now make an individual request for
each instance id (we do make these requests in parallel though).
> Change single multi-instance table query to many parallel queries

- src/DurableTask.AzureStorage/MessageManager.cs
This code path is important to protect, as blobs can often be quite
large which means the requests take longer and are more likely to be
interupted by network issues.
This is going to be replaced shortly by the AzureStorageClient refactor,
but this is easy enough to squeeze into 1.8.8.
> Add Storage deadlock mitigation to MessageManager

- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
- test/DurableTask.AzureStorage.Tests/OrchestrationInstanceStatusQueryConditionTest.cs
Minor issue I discovered while running a Java app against this backend. I didn't mean to provide an empty instance ID, but I do expect we handle it more gracefully if one does show up.
Also added nullable type information to the updated file as part of slowly modernizing this codebase.
> Fixed an InvalidOperationException if an empty string is provided for an instance ID query

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- tools/DurableTask.props
The previous fix #560 was not actually released as the fix is contained
in DurableTask.Core, which was not released as a part of
DurableTask.AzureStorage v1.8.8.
The fix in #560 is more severe than we thought as it makes a
TaskHubWorker lose an entire partition when it completes an
orchestration, so we are also releasing a new version of
DurableTask.AzureStorage that depends on DurableTask.Core having this
fix.
> Prepare DurableTask.Core and DurableTask.AzureStorage release

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
- src/DurableTask.AzureStorage/Storage/BlobContainer.cs
Updated BlobContainerPublicAccessType on CreateIfNotExistsAsync in BlobContainer that was causing an error with storage accounts without public blob access.
Updated AzureStorageClient constructor by removing storageAccountName. AzureStorageClient now sets it's own StorageAccountName.
> Fixed bug with BlobContainer permissions

- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
Some of the warnings being emitted by the SafePartitionManager happen
more frequently than initially thought, but are not really a concern. To
avoid taking up too much App Insights space and concerning customers
with unnecessary noise, we are removing these logs.
> Remove noisy logs in SafePartitionManager

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
This PR addresses a race condition leading to a NullReferenceException when starting an orchestrator.
When the instances table is not yet updated, OrchestrationSessionManager throws a NullRef on InstanceId after attempting to query for existing OrchestrationStates here:
https://github.com/Azure/durabletask/blob/6be1e3a2a23b81fdf681147c9b433610915adfae/src/DurableTask.AzureStorage/OrchestrationSessionManager.cs#L218
This fix changes the result returned from GetStateAsync, called above, to only return non-null OrchestrationStates.
> Fixed NullRef when querying instance status on execution started

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
Failing to deserialize a control queue message can result in orchestrations getting stuck and lots of duplicate message warnings to be logged. This is because we don't properly abandon the message after we've dequeued it. The result is that the orchestration service internally thinks we're still holding onto the message and refuses to process any new dequeued copies of the message.
We observed a case with users in the M365 org where orchestrations would get stuck for extremely long periods of time. When this happens, only a lease failover or a machine restart would cause the orchestration to continue. When investigating, we noticed two things:
* There were many "Received a duplicate message" warnings for the same message, one every 5 minutes. There was also no "MessageReceived" trace when …
> DT.AzureStorage: Fix a missed exception handling scenario

- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
This PR updates AzureTableTrackingStore to no longer manually create the filter condition for TableQuery, instead using the TableQuery methods to generate it for us.
In GetHistoryEventsAsync, we generated the filter condition containing InstanceId. If customers used an apostrophe in their InstanceId this query would fail as a bad request. Using TableQuery.GenerateFilterCondition handles this case for us and generates a filter condition that does not result in a bad request.
All manual filter condition creation code has been swapped with TableQuery generation methods.
> Updated TableQuery filter condition string generation

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
Pending orchestrations for large messages stored in blobs in the Azure
Storage implementation stored the blob name in the Input field in the
status table. This does not comply with the expectations that the
Input/Output fields should have either the raw value or an absolute URL
to the blob containing the raw values.
This PR addresses replaces the blob name with the blob URL.
> Fix large inputs for pending orchestrations on Azure Storage

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- tools/DurableTask.props
This is to fix a build signing issue in the alternate release pipeline (azure-pipelines-release.yml)
> Update DurableTask.props to work with different sln file locations

- samples/DurableTask.Samples/DurableTask.Samples.csproj
- src/DurableTask.Core/TaskOrchestrationContext.cs
- test/DurableTask.ServiceBus.Tests/DispatcherTests.cs
Current checks for nondeterminism are fairly limited, and only catch
major control flow changes. This PR attempts to improve our best-effort
attempts to catch non-determinism by validating that this replay's api
call signatures match the API calls scheduled by the orchestration
originally.
Resolves #594.
> Add more robust determinism checks in orchestration replay logic

- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Emulator/LocalOrchestrationService.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationHistoryEventEntity.cs
This PR makes a few `JsonSerializerSettings` static. This was partially a result of profiling `AzureTableOrchestrationHistoryEventEntity` behavior when reading/writing entities. `JsonSerializerSettings` isn't the smallest class, allocating it less won't hurt 😉
> JsonSerializerSettings made static

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
When you instantiate AzureStorageOrchestrationService like this it hangs because AccountName isn't set on StorageCredentials when they're created this way:
```
WindowsAzure.Storage.Auth.TokenCredential storageTokenCredential = ...
WindowsAzure.Storage.Auth.StorageCredentials storageCreds = new WindowsAzure.Storage.Auth.StorageCredentials(storageTokenCredential);
AzureStorageOrchestrationServiceSettings orchestrationServiceSettings = new AzureStorageOrchestrationServiceSettings
{
TaskHubName = "task hub name",
StorageAccountDetails = new StorageAccountDetails
{
AccountName = "XYZ",
StorageCredentials = storageCredentials
}
};
AzureStorageOrchestrationService orchestrationService = new AzureStorageOrchestrationService(orchestrationServiceSettings);
```
I'm trying to use Durable Task …
> Ensure storageAccountName is set correctly.

- Test/DurableTask.AzureStorage.Tests/ScheduleTaskTests.cs
- src/DurableTask.Core/TaskOrchestrationContext.cs
This PR changes the behavior to return the default value of a type instead of a `NullReferenceException` when a user calls `CallActivityAsync()` with a typed call (e.g. `await context.CallActivityAsync<bool>("MyFunctions_RunTaskAsync", input)`) and expects a Task, but the function returns void.
Example from GitHub issue:
```
[FunctionName("MyFunctions_RunTaskAsync")]
public async Task RunTaskAsync([ActivityTrigger] string input)
{
...
}
```
```
await context.CallActivityAsync<bool>("MyFunctions_RunTaskAsync", input);
```
```
Function 'MyFunctions (Orchestrator)' failed with an error.Reason: System.NullReferenceException: Object reference not set to an instance of an object.
at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskToWorker[TResult](String name, String version, String …
```
> Fix exception when Task returns void

- tools/DurableTask.props
Updating from 2.5.6 to 2.6.0 since new public API surface area has been added to both DT.Core and DT.ServiceBus, specifically #625, #623, and #595.
> Increment version for DT.Core and DT.ServiceBus

- src/DurableTask.AzureStorage/Partitioning/AppLeaseManager.cs
AppLeaseManager is currently using MD5 to create a hash of the appName used for appLeaseId, which is not FIPS compliant. This PR replaces that hash algorithm with an existing algorithm we use to group instanceIds to partitions.
resolves #637
> Updated AppLeaseManager hash algorithm to be FIPS compliant

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/Logging/LogEvents.cs
- src/DurableTask.AzureStorage/Logging/LogHelper.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
I was debugging a customer issue and noticed that it would be really nice if the _FetchedInstanceStatus_ log event had more information. This PR adds the following columns:
* **ExecutionId**: We already had this column, but it was always empty. This PR populates it with whatever execution ID we actually found in table storage.
* **RuntimeStatus**: This column is new and includes the status of the found orchestration instance or "NotFound" if none was found. This is helpful for debugging issues related to dedupe or for simply verifying what the status of an instance really is.
This is just a quality-of-life improvement for debugging.
> Improve FetchedInstanceStatus logs

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
Supersedes: https://github.com/Azure/durabletask/pull/639
**Bug description:** After enabling Distributed Tracing, Azure Table Storage would sometimes raise an exception claiming that some field exceeded the size limitations for an entry.  After investigation, it was determined that this field was the `Correlation` Property of the History table, which distributed tracing populates and relies upon.
**Root cause:** The cause of this issue was in the `UpdateStateAsync` method of `AzureTableTrackingStore`. Normally, our property-compression step (`CompressLargeMessageAsync`) should have avoided any size-limitation exceptions, but Distributed Tracing updates the `Correlation" field the History table with "raw correlation data" *after* the compression step.
**How to fix (this PR):** This …
> Patch correlation compression

- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Fixes https://github.com/Azure/durabletask/issues/650.
The fix is to essentially short-circuit out of de-dupe detection if the Instances table has a record with a null value for ExecutionId. This will be true only for orchestrations that are started with clients on v1.8.4 or earlier (ExecutionId wasn't added until after the orchestration checkpointed once). For newer clients that do add ExecutionId when scheduling an orchestration, de-dupe detection should continue to work as normal - no change in behavior.
> Fix compatibility issue between older clients and newer workers on DT.AzureStorage

- Test/DurableTask.Core.Tests/RetryInterceptorTests.cs
- src/DurableTask.Core/RetryInterceptor.cs
The final sleep inside the retry loop is redundant. 
The sleep period should take place between two retries. 
For example: If the max number of attempts is three, the total number of sleep periods should be two, as illustrated below.
This effect is amplified when retry intervals are relatively big (e.g., 30 mins), leading to undesirable side effects in the client code.
I created a couple of test cases reproducing the defect and verifying that the applied fix is working as intended.
> Fix retry interceptor sleeps

- src/DurableTask.Core/DurableTask.Core.csproj
This PR updates the System.Diagnostics.DiagnosticSource package from 4.6.0 to 5.0.1.
Note: Updating the package to the latest version (v6.0.0) shows many errors in the test projects.
Resolves #602
> Updating System.Diagnostics.DiagnosticSource version

- Test/DurableTask.Core.Tests/RetryInterceptorTests.cs
- src/DurableTask.Core/RetryInterceptor.cs
- tools/DurableTask.props
PR https://github.com/Azure/durabletask/pull/652 introduced a breaking change in history replay by removing a timer from the history when a retry policy executes all retries. The fix was "correct", but it was a breaking change for existing orchestration instances. This PR re-introduces the removed timer to fix the breaking change but sets the final timer delay to zero seconds to mitigate the impact of scheduling an extra timer.
This PR also updates the C# version to 9.0 in order to allow nullable generic type references.
> Fix retry interceptor regression

- azure-pipelines-release.yml
Includes SBOM-generation task to our pipeline, which documents our dependencies for cybersecurity compliance, It also uses the new 1ES-approved VM, another compliance requirement.
> Add SBOM task to release pipeline

- samples/DurableTask.Samples/DurableTask.Samples.csproj
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
- test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.csproj
Fixes [CVE-2018-8269](https://github.com/advisories/GHSA-mv2r-q4g5-j8q5)
Upgrades Microsoft.Data.OData from v5.6.4 to v5.8.5 (latest version) and other packages that depend on Microsoft.Data.OData:
- System.Spatial
- Microsoft.Data.Edm
- Microsoft.Data.Services.Client
Verified that there were no vulnerabilities after these changes by running `dotnet list package --vulnerable`
> Update packages to address CVE-2018-8269

- Test/DurableTask.AzureStorage.Tests/Storage/StorageUriExtensionsTests.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Partitioning/AppLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
- src/DurableTask.AzureStorage/Partitioning/LegacyPartitionManager.cs
- src/DurableTask.AzureStorage/Partitioning/SafePartitionManager.cs
- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
- src/DurableTask.AzureStorage/Storage/Blob.cs
- src/DurableTask.AzureStorage/Storage/BlobContainer.cs
- src/DurableTask.AzureStorage/Storage/Queue.cs
- src/DurableTask.AzureStorage/Storage/StorageUriExtensions.cs
- src/DurableTask.AzureStorage/Storage/Table.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
The Azure Storage account name is used for logging messages, but it may not be specified when Azure Storage Account Service URIs are supplied directly. However, while deriving the account name implicitly brings its own challenges, it also surfaces an additional question: what happens when the service accounts are different?
In this PR, I've made the following changes:
- Remove `StorageAccountName` from `AzureStorageClient` and replace it with `BlobAccountName`, `QueueAccountName`, and `TableAccountName`
- When the account name isn't specified explicitly, the account name is instead derived from each service URI based on the storage SDK's logic
- Use these new properties in lieu of the general `StorageAccountName` property based on which service is in use
- For general log messages, when …
> Allow Implicit (and Multiple) Azure Storage Accounts for Services

- src/DurableTask.AzureStorage/Storage/Queue.cs
Updated queue time to live to infinite to avoid messages from being deleted after 7 days resulting in stuck orchestrations.
resolves #660
> Updated Queue TTL to infinite

- samples/DistributedTraceSample/Program.cs
- src/DurableTask.Core/History/EventRaisedEvent.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
This PR adds distributed tracing for external events and builds on PR #648.
There are 2 main scenarios that this PR covers for External Events;
1. An event is raised using `OrchestrationContext` by calling `context.SendEvent()`
2. An event is raised using `TaskHubClient` by calling `client.RaiseEventAsync()`
Resolves #563
> Adding external events tracing

- src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
- src/DurableTask.AzureStorage/SimpleBufferManager.cs
This PR changes the `BlobLeaseManager` to use the `SimpleBufferManager` when reading the lease blobs. This is done since the call to `DownloadTextAsync` results in allocation of a new `MemoryStream`, which allocates a new `byte[]`. For high performance services, such allocations have a high impact on performance and GC times.
> Use the SimpleBufferManager when downloading Lease blobs

- azure-pipelines-release.yml
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.nuspec
This PR adds the SBOM manifest to the DurableTask.AzureStorage Release NuGet package. It adds a dotnet publish step and moves the manifest generator step to come before the dotnet pack step. It also adds a .nuspec file that specifies the additional files that need to get added to the NuGet package during dotnet pack.
> Add SBOM to DurableTask.AzureStorage Release NuGet package

- DurableTask.sln
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
This PR includes end to end tests that check traces after running orchestrations. The tests include an orchestration that calls an activity and also includes orchestrations that handle external events.
> Adding OpenTelemetry tests

- azure-pipelines-release.yml
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/DurableTask.Core.nuspec
- src/DurableTask.Emulator/DurableTask.Emulator.csproj
- src/DurableTask.Emulator/DurableTask.Emulator.nuspec
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.nuspec
This PR adds an SBOM manifest to the DurableTask.Core, DurableTask.ServiceBus, and DurableTask.Emulator Release NuGet packages. It adds a dotnet publish step for each project in the release pipeline. Each project also includes a .nuspec file now that specifies the additional files that need to get added to the NuGet package during dotnet pack.
> Add SBOM to DT.Core, DT.ServiceBus, and DT.Emulator Release NuGet packages

- src/DurableTask.Core/TaskOrchestrationContext.cs
When debugging a failing test in Connor's integration tests azure/azure-functions-durable-extension#1979 today I noticed an oddity: on completed OrchestrationWorkItems, any events sent by the orchestration appeared in reverse order in the runtime state. I tracked this down to TaskOrchestrationDispatcher, which returns the orchestrator actions as follows:
```csharp
public IEnumerable<OrchestratorAction> OrchestratorActions => this.orchestratorActionsMap.Values;
```
but this is actually nondeterministic (and happened to be in reverse order for me) because the map is just a plain dictionary:
```csharp
this.orchestratorActionsMap = new Dictionary<int, OrchestratorAction>();
```
I am a bit surprised that this has not been noticed before and has not caused more issues. The particular test that …
> Keep orchestrator actions sorted, to avoid out-of-order events in OrchestrationRuntimeState

- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/FabricOrchestrationProviderSettings.cs
- src/DurableTask.AzureServiceFabric/Service/TaskHubProxyListener.cs
- src/DurableTask.AzureServiceFabric/Tracing/ServiceFabricProviderEventSource.cs
* DurableTask.Core library supports emitting structured logs if an `ILoggerFactory` is provided during `TaskHubWorker` or `TaskHubClient` creation. This pull requests adds an option to provide the logger as part of `FabricOrchestrationProviderSettings` which is then passed into the initialization of `TaskHubWorker` or `TaskHubClient` objects.
* Updated the verbosity level for `LogStoreCount` trace. This trace is more like a counter which is emitted every minute for all reliable collections, reporting the number of objects in the collection. This can turn out to be very noisy, and drowning out other legitimate traces.
* I have not yet converted the ServiceFabric traces into structured logs. That will come in as part of a future PR
> Adding an option to log structured events via LoggerFactory in Service Fabric provider

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.nuspec
- src/DurableTask.Core/DurableTask.Core.nuspec
- src/DurableTask.Emulator/DurableTask.Emulator.nuspec
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.nuspec
This PR fixes the license in the .nuspec files from MIT to Apache 2.0.
> Update license in .nuspec files

- src/DurableTask.Core/TaskHubWorker.cs
- test/DurableTask.ServiceBus.Tests/DispatcherTests.cs
This change does the following:
* Adds a new non-generic `AddTaskActivitiesFromInterface` overload that lets the caller pass in a type instead.
> Add Non-Generic Overload for AddTaskActivitiesFromInterface

- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
Added ArgumentException catch block when attempting to steal a lease. This can be thrown when another worker steals the lease before we get to it.
resolves #406
> Added ArgumentException catch block when stealing lease

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/OrchestrationInstanceStatus.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.Core/History/ExecutionStartedEvent.cs
- src/DurableTask.Core/OrchestrationState.cs
This PR addresses issues when running dedupe orchestration started checks when reusing instanceIds. Currently if the instances table hasn't been updated by the time the dedupe checks run, the execution stated event can be discarded if the instanceId was reused. This is because the remoteInstance will be the previous instance execution, instead of the current instance execution. This PR addresses this issue by adding the column Generation to the Instances table, which represents the sequence number of each instance to ensure the correct execution is being represented in remoteInstance.
> Added Generation to ExecutionStartedEvent for Dedupe Checks

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Tracking/TableEntityConverter.cs
Found this while debugging Durable Functions CI failures. The issue is that new properties on history events are not handled correctly when they are not reference types. For example, the `ExecutionStartedEvent.Generation` property. Casting to `int?` or `long?` instead of `int` or `long` fixes the issue.
> Fix DT.AzureStorage regression caused by new Generation property.

- src/DurableTask.Core/Serializing/JsonDataConverter.cs
Use `using` when working with IDisposable objects. This allows better memory management by the GC.
> Use `using` for disposable objects

- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
- src/DurableTask.AzureStorage/Storage/Blob.cs
This fixes a bug in the partition management logic for ownership leases: all available ownership leases (for partitions that are expired and for which intent leases are owned) must be acquired, regardless of how many nodes there are and how many partitions have been already acquired. The balancing is already taken care of by the intent leases.
Also, this PR adds an exclusion so lease renewals are not subjected to request throttling; because request throttling on lease renewals can be counterproductive in heavily loaded situations.
> Fixes for new partition management

- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
- src/DurableTask.AzureStorage/Partitioning/SafePartitionManager.cs
This is a continuation of my other PR, _Improve logging for lease management #723_, that fixes a couple issues I discovered while doing some manual testing of the startup/shutdown sequence.
* **Remove misleading "lease lost" log message during shutdown**: This is likely an artifact from when we originally designed the "safe" partition balancer. Basically, whenever we shutdown either the intent lease or the ownership lease, we also attempt to "release" the control queue. However, since both lease managers try to release the same control queue, we were logging redundant and misleading messages about releasing something that was already released.
* **Make lease release serial instead of parallel for better determinism**: Debugging the behavior of lease removal was difficult because we …
> Additional Azure Storage lease management fixes

- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationWorkItem.cs
Currently, the TaskOrchestrationDispatcher, when completing a work item, does a tricky thing with the `OrchestrationRuntimeState` field of the work item:
1. replaces the new runtime state with the original runtime state object 
2. calls `CompleteTaskOrchestrationWorkItemAsync`
3. assigns it the new runtime state
This is a problem with the Netherite backend since the latter may immediately resubmit the workitem to continue the orchestration, causing a race condition with number 3 that leads to state corruption.
This PR adds a flag so that backends can turn off this behavior. 
_None of the other backends are affected since the flag is on by default._
> Add a backend-configurable flag to disable problematic OrchestrationRuntimeState behavior

- DurableTask.sln
- azure-pipelines-release.yml
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
This PR does a few primary things:
* Ensures the assembly version is always X.Y.0.0, making it easier to upgrade assembles for bug fixes. This is also more closely aligned with best practices based on learnings from the ASP.NET team.
* Ensures the file version is X.Y.Z.N, where N is a number from the CI or 0 locally, making it easier to distinguish locally built assemblies from CI-built assemblies (and to link them back to a particular CI run).
This is in response to the latest release where we had to upgrade both DT.Core and DT.AzureStorage even though we only made bugfix changes to DT.Core.
I also incremented the minor versions as part of this PR since the assembly versions would be going backwards with this change if we did another patch release.
> Improve versioning of DT.Core and DT.AzureStorage

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Storage/Table.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
Resolves https://github.com/Azure/azure-functions-durable-extension/issues/2211 (though perhaps not perfectly).
This PR makes batch purging more efficient in the following ways:
1. Scan the Instances table in multiple batches rather than scanning the whole thing in one go. This will result in decreased memory usage and prevent purge operations from making zero progress in timeout scenarios.
1. Remove outputs from the result of the initial scan to reduce network bandwidth and memory usage
1. Execute purge commands in parallel rather than serially, reducing the total amount of time expected to purge the history.
I added a small amount of code cleanup as well as made some fixes related to storage operation counting that I found while working through this code.
> Make batch instance purging more efficient

- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/TimeoutHandler.cs
This PR allows users to configure the various settings of Timeout handling:
* MaxNumberOfTimeoutsBeforeRecycle
* StorageRequestsTimeout
* StorageRequestsTimeoutCooldown
This allows having more permissive handling in noise scenarios (e.g. when the Storage Account is shared with other scenarios), or unstable scenarios (e.g. when the Storage Account experiences longer delays).
> Make Storage timeouts handling configurable

- src/DurableTask.Core/OrchestrationContext.cs
- src/DurableTask.Core/TaskHubWorker.cs
- test/DurableTask.ServiceBus.Tests/SerializationTests.cs
This change extends `TaskHubWorker.AddTaskActivitiesFromInterface` by supporting adding activities from `abstract` or non-sealed classes.
> Support Add Task Activities from Abstract or Non-Sealed Class

- src/DurableTask.Core/Tracing/TraceHelper.cs
This PR updates the external event `Activity`'s `ActivityKind` value. [This link](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitykind?view=net-6.0) lists the `ActivityKind` enum values.
Resolves #718
> Update ActivityKind values

- src/DurableTask.Core/Tracing/TraceHelper.cs
This PR removes the explicit `parentContext` assignment while creating an `Activity` to allow traces from external services to correlate with DurableTask traces. Without setting `parentContext`, `StartActivity()` will internally set the current Activity as the parent.
The tags are also set after checking if `Activity` is null to improve memory management.
> Updating Activity initialization

- src/DurableTask.Core/ReflectionBasedTaskActivity.cs
This change simply exposes the generic overload of `ReflectionBasedTaskActivity.InvokeAsync`, the overloaded version is already public so this simply achieves parity.
> Make ReflectionBasedTaskActivity.InvokeActivity Public to Match Overload

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Redis/DurableTask.Redis.csproj
- src/DurableTask.SqlServer/DurableTask.SqlServer.csproj
The release pipeline recently started failing with the following error during `nuget restore`:
> D:\a\_work\1\s\src\DurableTask.AzureStorage\DurableTask.AzureStorage.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.SourceLink.GitHub 1.0.*, Microsoft.SourceLink.GitHub 1.0.*.
I believe this is due to the fact that both DurableTask.AzureStorage.csproj and the DurableTask.props file it imports both include this package reference. These changes were made > 3 years ago, so I think we're seeing this now because of [recent SDK updates](https://github.com/dotnet/sdk/issues/24747#issuecomment-1218481503) made by the .NET and/or …
> Remove redundant Microsoft.SourceLink.GitHub package references

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Logging/LogEvents.cs
- src/DurableTask.AzureStorage/Logging/LogHelper.cs
- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Storage/QueueMessage.cs
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/OrchestrationRuntimeState.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
There are two main changes in this PR, both motivated by IcM 331554589:
There are certain `MessageGone` scenarios that are difficult to debug because there is no pop-receipt information in the message traces. This PR adds this extra telemetry so that we can more easily see when the system is confused about which version of a message it is working with.
This change would have been useful in detecting a negative feedback loop situation where slow orchestration processing resulted in an infinite loop of dequeuing duplicate messages (the fix for the negative feedback loop problem is out of scope for this PR).
History corruption will often result in poison-message scenarios. The root cause of the corruption for this particular CRI appears to be related to duplicate sub-orchestration execution. …
> DT.AzureStorage: Poison message handling for corrupt orchestration state

- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/Logging/LogEvents.cs
- src/DurableTask.Core/Logging/LogHelper.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationExecutor.cs
DTFx code is often hosted in Azure App Service and Azure Functions. When running on these platforms, certain framework traces are captured into an internal log capturing service. One of the things logged by DTFx is exception messages for activity failures. These exception messages are often generated by user code, which may contain sensitive information (PII, secrets, etc.). 
As a safety mechanism, this PR will redact exception messages that come from activity failures. This redaction is enabled by default when hosted in an Azure App Service environment, which we infer by checking for the `WEBSITE_SITE_NAME` environment variable. This policy of redaction can be overridden by setting a `DTFX_REDACT_USER_CODE_EXCEPTIONS` environment variable to `1` or `true`.
This PR also adds additional …
> Enable redacting user-code exception messages

- src/DurableTask.Core/OrchestrationExecutionContext.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskMessage.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
Propagating OrchestrationRuntimeState to TaskActivity dispatcher middleware. This allows Tags and other historical events to be accessible from TaskActivity dispatcher middleware
> Propagating Orchestration Tags to TaskActivity

- Test/DurableTask.ServiceBus.Tests/TestObjectCreator.cs
- samples/Correlation.Samples/Correlation.Samples.csproj
- samples/DurableTask.Samples/App.config
- samples/DurableTask.Samples/DurableTask.Samples.csproj
- samples/DurableTask.Samples/Program.cs
- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
- test/DurableTask.ServiceBus.Tests/DispatcherTests.cs
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
- test/DurableTask.ServiceBus.Tests/DynamicProxyTests.cs
- test/DurableTask.ServiceBus.Tests/ErrorHandlingTests.cs
- test/DurableTask.ServiceBus.Tests/FunctionalTests.cs
- test/DurableTask.ServiceBus.Tests/RuntimeStateStreamConverterTest.cs
- test/DurableTask.ServiceBus.Tests/SampleScenarioTests.cs
- test/DurableTask.ServiceBus.Tests/TestHelpers.cs
- test/DurableTask.ServiceBus.Tests/app.config
- test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.csproj
- test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.dll.config
- test/DurableTask.Stress.Tests/Program.cs
- test/DurableTask.Stress.Tests/app.config
Given the deprecation of the Service Bus backend, changes to the Durable Task Framework and its related packages should not be back-ported to the Service Bus package (unless explicitly desired). However, there are a number of project references to the Service Bus backend including samples, integration test, and stress tests. To avoid making future unnecessary changes to the Service Bus backend, I have created this PR where I isolate it from the other projects with the following changes:
- Replace Service Bus with Azure Storage in both the sample and stress tests projects
- Removal of dependencies on other projects from the Service Bus test project
- This involved the duplication of one class, one method, and the inclusion of test orchestrations for compilation
- .NET Framework refactors …
> Replace Service Bus Backend in Samples and Stress Tests

- src/DurableTask.Core/DurableTask.Core.csproj
This is in preparation for a release, which has been requested by an internal team. The primary change is https://github.com/Azure/durabletask/pull/804.
> Increment DT.Core to v2.12.0

- test/DurableTask.ServiceBus.Tests/DispatcherTests.cs
This test is failing consistently in the CI and has been known to be flaky for a while. It's not clear what it does or why it's failing. The Service Bus project also doesn't have any dedicated maintainers, so disabling this test for now to unblock the CI for accepting other PRs.
> Disable flaky test: MessageLegacyCompressToAlwaysCompressTest

- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
There is a bug in `Microsoft.Azure.ServiceBus` with net6 where all messages fail to dequeue (making it completely unusable). This PR updates our referenced package to address this issue.
- `Microsoft.Azure.ServiceBus` package changed from 4.1.3 to 4.2.1
- `Microsoft.Azure.DurableTask.ServiceBus` package version changed from 2.6.0 to 2.7.0 (minor version chosen to reflect minor version change in dependency)
resolves #815
> Update ServiceBus dependency to fix net6 bug

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
An internal partner team noticed an issue where the Instances table gets populated with a wrong blob URL when an orchestration is started with a large input (one that doesn't fit into table storage). Specifically, the `Input` column/property was getting populated with the blob URL of the queue message instead of with a blob URL for the orchestration's input.  This was causing orchestration status queries to return the wrong input data.
Upon investigation, it looks like this issue has existed for a while but just went undetected. I was able to observe the problem by updating some existing unit tests to validate the reported orchestration input when large inputs are used.
~~The fix was to remove some code that was causing us to populate the `Input` column/property incorrectly.~~
EDIT: The …
> Fix wrong blob URL on orchestration inputs

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- test/DurableTask.AzureStorage.Tests/OrchestrationInstanceStatusQueryConditionTest.cs
This is in preparation for a bug-fix release of DurableTask.AzureStorage.
I also slipped in a new unit test that had been on my local machine but never contributed as a PR (it seemed too insignificant to create a separate PR just for that, hence the bundling).
> Increment version of DT.AzureStorage to v1.13.2

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
If an orchestration is started with tag data that exceeds the maximum allowed size for table storage columns when using the DurableTask.AzureStorage backend, the orchestration will cause the following exception (possibly repeatedly):
```
DurableTask.AzureStorage.Storage.DurableTaskStorageException: Element 1 in the batch returned an unexpected response code.
---> Microsoft.WindowsAzure.Storage.StorageException: Element 1 in the batch returned an unexpected response code.
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, …
```
> DT.AzureStorage: Fixed exception when orchestration tags are too large

- azure-pipelines-release.yml
This ESRP signing step of the DTFx release pipeline is failing because the build images no longer include .NET Core v2.1. This PR explicitly installs that version of .NET so that the ESRP steps can run successfully.  This is the same step we use for pretty much all of our other existing release pipelines, so I'm surprised we didn't have it already for this one.
> Add .NET 2.1 to release pipeline

- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
Added a more specific log to the ControlQueue shutdown process to identify which token was cancelled to trigger the shutdown.
> Improved ControlQueue shutdown logs

- samples/DistributedTraceSample/Program.cs
- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/Tracing/DiagnosticActivityExtensions.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
Creating this PR as a replacement of #694 to clean up the commit history. The code changes are similar to the previous PR. This PR adds exception information to spans when an orchestration or activity throws an exception. It also adds `Activity` extension methods for `SetId()`, `SetSpanId()`, and `SetStatus()`. 
The following examples cover both `ErrorPropagationMode` settings
1) HelloSequenceException orchestration with the following `TaskHubWorker` settings
```
worker.ErrorPropagationMode = ErrorPropagationMode.UseFailureDetails;
worker.TaskActivityDispatcher.IncludeDetails = true;
worker.TaskOrchestrationDispatcher.IncludeDetails = true;
```
2) ExceptionSubOrch orchestration with the following `TaskHubWorker` settings
worker.ErrorPropagationMode = …
> Adding exception information to spans (Replaces #694)

- src/DurableTask.Core/Logging/EventIds.cs
- src/DurableTask.Core/Logging/LogEvents.cs
- src/DurableTask.Core/Logging/LogHelper.cs
- src/DurableTask.Core/Logging/StructuredEventSource.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
This PR addresses a known weakness of the existing `TaskOrchestrationDispatcher`, namely that it does not always renew work items with the `IOrchestrationService`, which means they may expire prior to completing (see #112).
While this is rarely a problem (because typical orchestration work items complete very quickly) it has caused issues with entities in environments where long-running entity operations are used (see Azure/Azure-Functions#2337).
This PR fixes this problem.
- automatically renews TaskOrchestrationWorkItems in a expiration-time-based loop until they complete.
- adds a unit test to check that the renewal works.
> Implement orchestration work item renewal

- src/DurableTask.AzureStorage/MessageManager.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
This issue is originally mentioned in [this comment](https://github.com/Azure/durabletask/pull/853#discussion_r1087081311) from PR #853.
This PR adds a format check for the message before creating a URI. There are some cases where `Uri.TryCreate()` doesn't check the format of its input and `Uri.IsWellFormedUriString()` covers those cases.
> Add format check for blob Urls

- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/Tracing/Schema.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
This PR updates the distributed tracing with OpenTelemetry code based on the spec in #847.
Scenarios from the spec that are not addressed:
- Span Status (e.g. OK, ERROR) (refer to comment in this PR for discussion)
- Fire and forget sub-orchestrations (not supporting for early preview)
- Event links (based on the conversation in the spec, it looks like we need to discuss the user experience more after the early preview)
> Update distributed tracing code based on spec

- Test/DurableTask.AzureStorage.Tests/MessageManagerTests.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/ICustomTypeBinder.cs
- src/DurableTask.AzureStorage/MessageManager.cs
Allow custom type binding for system types, Fixing #877
We are solving the deserialization problem by allowing configuration based bindings.
We cannot get rid of the Type handling in general due to the inheritance based logic used after deserialization.
> Allow customizing type binding for dequeued Azure Storage messages

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/Common/Utils.cs
- src/DurableTask.Core/DurableTask.Core.csproj
This will remove certain static analysis warnings due to vulnerabilities. At runtime, our dependency is already being replaced with the newtonsoft.json version brought in by WebJobs, which is already `13.0.1`, so this change should be safe.
The change also required that we update the code in a few places to account for the possibility of the deserialization returning `null`. You will a few types being updated to include the `?` modifier as a result.
> Update newtonsoft.json from 11.0.2 to 13.0.1

- Test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
- src/DurableTask.Emulator/DurableTask.Emulator.csproj
- test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
- test/DurableTask.Test.Orchestrations/DurableTask.Test.Orchestrations.csproj
Follow up to: https://github.com/Azure/durabletask/pull/870
It appears that CI did not run on the PR above, leading to broken tests post-merge. This PR fixes that by updating our Newtonsoft references across the test projects
> Patch tests post Newtonsoft.Json upgrade to 13.0.1

- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
When using a TrackingStore that is in a different account, blobs should also be stored in that account so they stay together with the instance and history tables.  
fixes #879.
> DT.AzureStorage: fix blob account for TrackingStore

- src/DurableTask.Core/History/SubOrchestrationInstanceCreatedEvent.cs
- src/DurableTask.Core/History/TaskScheduledEvent.cs
- src/DurableTask.Core/ISupportsDurableTraceContext.cs
- src/DurableTask.Core/OrchestrationRuntimeState.cs
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
This PR updates the `ActivityKind` values for task activity spans and also makes the task activity client span the parent of the task activity server span.
> Update task activity ActivityKind values and parents

- Test/DurableTask.AzureStorage.Tests/Storage/TableClientExtensionsTests.cs
- src/DurableTask.AzureStorage/Storage/TableClientExtensions.cs
I fixed a [bug with `TableClient.Uri`](https://github.com/Azure/azure-sdk-for-net/pull/35566) yesterday related to the Azurite URL, but I also realized the implementation I wrote here did not account for possible SAS tokens in the table endpoint. So this change incorporates it.
I also re-merged with main because apparently some history was not included 😦 We probably shouldn't squash for changes into the feature branch
> Fix TableClient.Uri When Endpoint Contains SAS Tokens

- src/DurableTask.AzureServiceFabric/FabricOrchestrationService.cs
- src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Stores/SessionProvider.cs
This PR is handling the following cases:
1. When an orchestration is terminated, sometimes it's adding a TerminateEvent message to a non-existent instance id or execution id
2. If we clean up the session store then the in-memory session queue may still contain an entry which tries to find an already cleaned up session.
> [AzureServiceFabric] Handle missing ExecutionStartedEvent orchestrations

- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/FabricOrchestrationService.cs
- src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Remote/RemoteOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Stores/SessionProvider.cs
- src/DurableTask.AzureServiceFabric/Utils.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/FunctionalTests.cs
Summary of changes:
1. Fix: Terminating an already finished orchestration causes Terminate event left out in the session provider. It causes "System.InvalidOperationException: An ExecutionStarted event is required."
2. Fix: When an orchestration is terminated, an already running task is left out in the ActivityProvider queue causing the activity provider to choke.
3. Fix: Cleanup the orchestration that exists without ExecutionStartedEvent upon Release
4. Added more test cases to test Terminate orchestration
> [AzureServiceFabric] Fix issues related to Terminate orchestration

- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
Stop Continue-as-New when runtime state already in terminated status
Related issue: https://github.com/Azure/azure-functions-durable-extension/issues/2264
> Fix exception when Continue-as-New and Termination happens at the same time

- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/FabricOrchestrationService.cs
- src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Remote/RemoteOrchestrationServiceClient.cs
- src/DurableTask.AzureServiceFabric/Stores/SessionProvider.cs
- src/DurableTask.AzureServiceFabric/Utils.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationHistory.cs
- src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/FunctionalTests.cs
Merge main branch and resolve conflicts, specifically arising from https://github.com/Azure/durabletask/pull/891
> Merge Main into Azure Storage v12 Branch

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
This PR validates that the timeout in WaitForOrchestrationAsync is positive. Otherwise, we risk accidentally returning `null` without doing any meaningful work.
This PR also enables nullable analysis for part of the `AzureStorageOrchestrationService` file
I encountered this in the process of repro'ing this issue: https://github.com/microsoft/durabletask-dotnet/issues/143
> Validate that timeout is positive in WaitForOrchestrationAsync, and enable nullable checks

- src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
To enhance the logging clarity in the `GetMessageAsync` method, update the log to include both lease loss and shutdown as cancellation reasons. This will provide more detailed information in the Kusto logs.
**Old implementation**:
When least lost happened, the method still logged cancellation reason as `shutdown`. 
**Update**:
when queues are released due to lease loss, the log specifies the reason as `lease lost` rather than `shutdown`.
> Update Log Info for GetMessagesAsync

- src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
- src/DurableTask.AzureServiceFabric/Service/DefaultDependencyResolver.cs
Previous implementation used a single root scope for all HTTP requests. As the scope was never disposed, so didn't the controller & HTTP request/response objects, causing them to get accumulated in memory.
This change creates a new scope in `BeginScope()` API which will be disposed by request handler when the request completes. More information can be found here: [Dependency Injection in ASP.NET Web API 2 - ASP.NET 4.x | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/dependency-injection#dependency-scope-and-controller-lifetime)
> SF Provider: memory leak: Create a new scope in HTTP controller DI on each BeginScope call

- docs/telemetry/traces/semantic-conventions.md
- semantic-conventions.md
This PR adds a spec that outlines the semantic conventions we are using to implement distributed tracing in the DurableTask Framework. It follows the [Open Telemetry Trace Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions "Open Telemetry Trace Semantic Conventions").
Additional information:
The image below is an example of a distributed trace created from the current instrumentation implementation. Each blue or red bar (solid and dashed) is a **span**. The properties on the right are the span's **attributes**. The group of spans in this image make up a **trace**.
> Add Distributed Tracing spec

- src/DurableTask.AzureStorage/OrchestrationInstanceStatus.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/TagsSerializer.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
This change adds a property to the Azure tracking table ("Tags") that will store the tags for an orchestration. If it is too large, it is offloaded to a blob rather than being stored as a property.
As part of this change, `OrchestrationInstanceStatus` from the table is no longer created with reflection; instead, properties are searched for and then set on the status DTO.
Fixes #840
> Enable Tags to be surfaced via TaskHubClient

- src/DurableTask.AzureServiceFabric/Service/FabricOrchestrationServiceController.cs
- src/DurableTask.Core/Tracing/DistributedTraceContext.cs
- test/DurableTask.AzureServiceFabric.Integration.Tests/FunctionalTests.cs
Service Fabric Provider's `TaskHubClient` expects HTTP 409 in order to process `OrchestrationAlreadyExistsException`, however, the service was throwing HTTP 400 instead, causing the error to be treated as an unknown service error.
Sample response the client receives where the `OrchestrationAlreasyExistsException` is left serialized inside the `RemoteServiceException` message string:
> DurableTask.AzureServiceFabric.Exceptions.RemoteServiceException: CreateTaskOrchestrationAsync failed with status code BadRequest: {"$type":"DurableTask.Core.Exceptions.OrchestrationAlreadyExistsException, DurableTask.Core","ClassName":"DurableTask.Core.Exceptions.OrchestrationAlreadyExistsException","Message":"An orchestration with id '725779b1-b39f-4428-8568-98690f6b4872' is already …
> SF Provider: Fix OrchestrationAlreadyExists status code from 400 to 409

- src/DurableTask.Core/Entities/ClientEntityHelpers.cs
- src/DurableTask.Core/Entities/StateFormat/EntityStatus.cs
- src/DurableTask.Core/Entities/StateFormat/SchedulerState.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
Three changes here:
- on the entity scheduler state: since we are maintaining the invariant (entity exists) <=> (serialized state is not null) there is no reason for defining (and serializing/deserializing) an `entityExists` field. Instead, just use a property.
- in client entity helpers, provide access to helper functions so external code can deserialize strings that represent `EntityStatus` and `SchedulerState` without us having to make the serialization format public.  This is needed by backends that provide entity query functionality directly. 
- also provide a shortcut (optimized) way to determine if an entity exists when looking at the entity status. Again, this is useful for backends implementing queries.
> Revise entity state and status format and access

- src/DurableTask.Core/Entities/OrchestrationEntityContext.cs
Previously, clients had to reconstruct this information on their own. Duplicating that logic seemed like a bad idea since it could easily get out of sync if there are future changes. Instead, we can just make this information accessible, which simplifies the clients.
> Make criticalSectionId of current critical section externally visible

- src/DurableTask.Core/Entities/OperationFormat/StartNewOrchestrationOperationAction.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
The entity SDK does not offer the ability to change the orchestration tags, so it is not necessary to include them in the `StartNewOrchestrationOperationAction` class.
When using this action, however, the `FireAndForget` tag is always added since entities always start orchestrations using fire-and-forget.
> remove orchestration tags from entity action

- src/DurableTask.Core/Entities/OperationFormat/EntityBatchRequest.cs
- src/DurableTask.Core/Entities/OperationFormat/EntityBatchResult.cs
- src/DurableTask.Core/Entities/TaskEntity.cs
- src/DurableTask.Core/Logging/LogEvents.cs
- src/DurableTask.Core/Logging/LogHelper.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
For better consistency across repositories and easier understanding, these are now named EntityBatchRequest and EntityBatchResponse.
> Rename OperationBatchRequest and OperationBatchResponse

- src/DurableTask.Core/Entities/EventFormat/ResponseMessage.cs
- src/DurableTask.Core/Entities/OperationFormat/OperationResult.cs
- src/DurableTask.Core/Logging/LogEvents.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
Revises the operation result representation and adds more comment.
> revise operation result encoding and add more comments.

- src/DurableTask.Core/Serializing/DataConverter.cs
- src/DurableTask.Core/Serializing/Internal/RawInput.cs
- src/DurableTask.Core/TaskHubClient.cs
This PR is to address a conflicting need in Durable Functions extension. We want to use `TaskHubClient` from within `LocalGrpcListener` so that we leverage all the logic there, especially the distributed tracing work. However, our input is already serialized and `TaskHubClient` would double serialize it. To work around this an "internal" API called `RawInput` has been added. When this type is used as the input for `TaskHubClient`, we will directly use `RawInput.Value` instead of serializing the input.
`RawInput` is "internal" in the sense that it is `public`, but in an `.Internal` namespace, with an `[Obsolete]` attribute, and xmldoc advising customers to use the type at their own risk. This is a pattern used in a few .NET libraries (efcore, webjobs, functions worker, etc) to address the …
> Add RawInput to workaround double-serialization issue

- src/DurableTask.Core/TaskOrchestrationContext.cs
Expanding the usage of `.SerializeInternal` to give a way to address https://github.com/Azure/azure-functions-durable-extension/issues/2589
Opting for this route so we don't need to deserialize and re-serialize the event input.
> Use SerializeInternal in TaskOrchestrationContext

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/EntityTrackingStoreQueries.cs
- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
- src/DurableTask.Core/Entities/EntityBackendProperties.cs
- src/DurableTask.Core/Entities/EntityBackendQueries.cs
- src/DurableTask.Core/Entities/IEntityOrchestrationService.cs
- src/DurableTask.Core/Query/OrchestrationQuery.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
- src/DurableTask.Core/TaskHubWorker.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
This PR does
1. simplify how features are supported via `IEntityOrchestrationService`. 
2. implements direct support for entity queries in the `AzureStorageOrchestrationService`.
> revise entity backend properties and implement entity backend queries

- src/DurableTask.AzureStorage/EntityTrackingStoreQueries.cs
- src/DurableTask.Core/Entities/EntityBackendQueries.cs
- src/DurableTask.Core/Entities/StateFormat/EntityStatus.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
Several changes here:
- rename 'includeDeleted' property to `includeStateless` because it is more accurate (there are other reasons than having been deleted why an entity could be stateless). Added a comment on this to explain a bit more.
- added `BackLogQueueSize` and `LockedBy` properties to the entity metadata returned by queries. This information was already being stored in storage but not returned by queries.
> Revise entity queries

- src/DurableTask.Core/Entities/OperationFormat/StartNewOrchestrationOperationAction.cs
- src/DurableTask.Core/TaskEntityDispatcher.cs
To keep APIs consistent, it makes sense to have the same options when starting orchestrators from clients or from entities.
To make this possible, this PR adds a scheduled time argument to the action.
> Add scheduled start time to start-new-orchestrator operation action

- src/DurableTask.AzureStorage/EntityTrackingStoreQueries.cs
- src/DurableTask.Core/Entities/EntityBackendQueries.cs
As discussed, we updated terminology across all repos to "transient entities" when talking about entities that do not have an application-defined state.
> Rename includeStateless to includeTransient in entity queries

- src/DurableTask.Core/TaskHubWorker.cs
Observed NullReferenceException when using durabletask with a backend that does not support entities, even if not using entities at all.
The reason is a missing '?' in the check that determines whether to use the old or new entity dispatch design.
The fix is to add the missing '?'.
> fix NullReferenceException on backends that do not implement IEntityOrchestrationService

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/TagsSerializer.cs
The System.Text.Json package refers to Systems.Buffer which is not supported in DurableFunctions V1 host. Replace this package with Newtonsoft.
> Replace STJ package with Newtonsoft

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
As titled. Remove DTFx.AS and DTFx.Core preview suffix for durable functions v2.13.0 public release.
> Remove DTFx.AS and DTFx.Core preview suffix for public release

- src/DurableTask.Core/Logging/EventIds.cs
- src/DurableTask.Core/Logging/LogEvents.cs
- src/DurableTask.Core/Logging/LogHelper.cs
- src/DurableTask.Core/Logging/StructuredEventSource.cs
- src/DurableTask.Core/OrchestrationRuntimeState.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
Replaces: https://github.com/Azure/durabletask/pull/901/files
From this feedback: https://github.com/Azure/durabletask/pull/901/files#r1316325503
Currently, we throw an exception if we receive multiple `ExecutionCompletedEvent`s. That behavior is a bit too strict because it is possible for multiple `ExecutionCompletedEvent`s to be received at once. For example: when a termination signal arrives at the same time as an orchestrator is requested to continue-as-new.
This PR introduces two changes to this behavior:
(1) Instead of throwing an exception like we do today, we now log a warning notifying the reader that we've found multiple execution completed events and how DTFx is resolving this conflict.
(2) If orchestrator is ~not in the terminated state and the a new event aims to terminate …
> Log warning on multiple execution completed events and allow termination to override previous execution completed events

- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
While investigating https://github.com/microsoft/durabletask-mssql/issues/198, I noticed that some of the new distributed tracing code casts history events based on certain assumptions, which aren't always true in production. The issue can result in a poison message with the following error:
```
System.InvalidCastException: Unable to cast object of type 'DurableTask.Core.History.TaskCompletedEvent' to type 'DurableTask.Core.History.TaskScheduledEvent'.
at DurableTask.Core.TaskOrchestrationDispatcher.ReconcileMessagesWithState(TaskOrchestrationWorkItem workItem, String dispatcher, ErrorPropagationMode errorPropagationMode, LogHelper logHelper) in //src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 860
at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestr …
```
> Fix InvalidCastException for history event type mismatch

- src/DurableTask.Core/TaskOrchestrationContext.cs
This PR fixes issue [#2519](https://github.com/Azure/azure-functions-durable-extension/issues/2519)
When calling SuspendAsync URL, condition can happen that the orchestrator is suspended when there is already an action scheduled and added to the `orchestratorActionsMap`. However, our design will add any later event into a temporary queue during suspended time. Thus, this scheduled action will never be removed or completed and will be executed endless times until orchestrator is resumed. And this execution history will also be added to the History Table which will cause the non-deterministic error when orchestrator is resumed. 
The race condition occurs when an `ExecutionSuspended` message is processed after `TaskCompleted`. Additionally, there is a subsequent activity task pending …
> Add orchestrator scheduled actions check when suspended

- src/DurableTask.Core/TaskHubClient.cs
As the title says it adds the override
```cs
public Task<OrchestrationInstance> CreateScheduledOrchestrationInstanceAsync(string name, string version, string instanceId, object input, DateTime startAt)
```
> Add new CreateScheduledOrchestrationInstanceAsync override to allow specifying name/version/instanceId & startAt

- DurableTask.sln
- src/DurableTask.Core/NameVersionHelper.cs
- src/DurableTask.Core/OrchestrationContext.cs
- src/DurableTask.Core/ScheduleProxy.cs
- src/DurableTask.Core/ScheduleProxyV2.cs
- src/DurableTask.Core/TaskHubWorker.cs
- test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs
there is a bug in `TaskHubWorker.AddTaskActivitiesFromInterface` where each method of a registered interface is keyed by a weak "qualified name" that hits collisions when using C# code reuse features such as inheritance, generics, method overloading.
This is reproducible even with `useFullyQualifiedMethodNames = true`.
This PR fixes by making a stronger qualified name in "V2" methods for task registration and client creation.
It is essential to keep the "V1" methods for back-compatibility.
> support task registration from interface with inheritance, generics, method overloading

- src/DurableTask.Core/TaskEntityDispatcher.cs
As reported in https://github.com/Azure/azure-functions-durable-extension/issues/2690, the `TaskEntityDispatcher` contains a bug where the input field is lost when creating a entity request message representing a signal.
> Fix bug where input is not passed along when signaling an entity

- src/DurableTask.Core/Entities/OrchestrationEntityContext.cs
As reported by microsoft/durabletask-dotnet#246, there is currently not always a descriptive error message when using a backend that does not support entities.
This PR adds checks to throw an exception if entity-features are used from within an orchestrator while using a backend that does not support entities. Such exceptions are thrown on the orchestrator thread, which should then cause the orchestrator to fail and log or otherwise propagate the error message.
> Add checks for entity support

- Test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
- src/DurableTask.Core/TaskActivity.cs
This PR adds a null check during error handling in `AsyncTaskActivity`. As described in #1054, if the `context` parameter is passed as null to `RunAsync`, and the call to `ExecuteAsync` fails for some task-specific reason, the error handling code uses that parameter to check which error propagation mode is being used. If the parameter is null, an unexpected `NullReferenceException` will be raised, instead of the expected `TaskFailureException`.
A null check is added to prevent this from happening.
> Add TaskContext null check in AsyncTaskActivity error handling

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
This is to allow exception handling code to catch a more specific exception and differentiate between unexpected errors and expected errors.
This is largely non-breaking because `OrchestrationAlreadyExistsException` already derives from `InvalidOperationException`.
Note that the `IOrchestrationServiceClient` interface already documents that the `CreateTaskOrchestrationAsync` methods should be throwing `OrchestrationAlreadyExistsException`, so this change fixes the AzureStorageOrchestrationService's implementation to follow the existing spec.
> Change CreateTaskOrchestrationAsync tp throw OrchestrationAlreadyExistsException

- Test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/Exceptions/OrchestrationException.cs
- src/DurableTask.Core/FailureDetails.cs
- src/DurableTask.Core/TaskOrchestrationContext.cs
First step towards properly fixing https://github.com/Azure/azure-functions-durable-extension/issues/2476.
This PR fixes a couple things:
1. The `IsCausedBy<T>()` API doesn't correctly handle exceptions defined outside of mscorlib. This PR fixes that.
2. Exception details aren't propagating correctly from a sub-orchestration to the parent orchestration. This PR also fixes the propagation.
3. Minor public API changes to make some of the failure details primitives usable by other SDKs
I also went ahead and bumped the minor version number of DurableTask.Core since these changes impact the public API surface area.
> New APIs and updates related to failure details propagation

- src/DurableTask.AzureStorage/EntityTrackingStoreQueries.cs
- src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
Branch `nytian/updateasv12`: Syncs updates between the main branch and azure-storage-v12.
Branch `nytian/merge_main` (feature branch): Built on branch `nytian/updateasv12`, this PR includes adjustments necessary for the integration of previous updates into Azure Storage Track2.
After this PR is approved and merged, then I will merge branch `nytian/updateasv12` to `azure-storage-v12`.
> Update Main Branch Changes with Azure Storage Track2 Methods

- test/DurableTask.SqlServer.Tests/DurableTask.SqlServer.Tests.csproj
As in title, due to CVE warning making builds difficult.
> Rev SqlClient dependency in SqlServer tests

- src/DurableTask.AzureStorage/MessageManager.cs
In this PR (https://github.com/Azure/durabletask/pull/503) we introduced the ability to use a DataContractConverter when de-/serializing to Json. However, in this PR (https://github.com/Azure/durabletask/pull/775) we moved the instantiation of the JsonConverter to occur _before_ the DataConverter is specified, which means the converter is ignored at de-/serialization time.
This PR fixes that by moving the JsonConverter instantiation to _after_ the DataConverter is provided.
**Open question: why did the unit tests in (https://github.com/Azure/durabletask/pull/503) not catch this regression?**
> Honor DataConverter when creating JsonConverters

- src/DurableTask.Core/TaskActivityDispatcher.cs
Looks like this log somehow got duplicated. Removing the first instance, since it occurs before a null-check and therefore seems at risk compared to the second instance (which is just a few lines below).
> Remove duplicate activity starting log message

- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/TaskEntityDispatcher.cs
Whenever core entities start, they will generate both `OrchestratorStarted` and `OrchestratorCompleted` events. The DetermineWork function checks all events of entities' runtime status. Therefore, the default error handling is not appropriate, as it should at least exclude these two events from being caught.
Fixes #1095
> Remove Wrong Core Entities Error Handling

- Test/DurableTask.Core.Tests/TaskHubClientTests.cs
- src/DurableTask.Core/TaskHubClient.cs
- src/DurableTask.Emulator/LocalOrchestrationService.cs
Related: https://github.com/Azure/azure-functions-durable-extension/pull/2805
In the PR above, we learned if a user wants to _schedule_ an orchestrator to start a particular time, they need to use the `CreateScheduledOrchestrationInstanceAsync` instead of using the more commonly used `CreateOrchestrationInstanceAsync` API. 
Allowing `CreateOrchestrationInstanceAsync` to also schedule orchestrators by accepting a new `fireAt` would simplify things downstream (in durabletask-dotnet, it would simplify the PR linked above^) so this PR adds that "missing" parameter. This does create some repetition (there are now two APIs that allow users to schedule orchestrators) but I think it makes the orchestrator-scheduling feature more discoverable while also helping simplify downstream code.
This PR …
> Allow TaskHubClient's CreateOrchestrationInstanceAsync to schedule orchestrators

- eng/ci/official-build.yml
- eng/templates/build.yml
- src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
This PR adds the basic "build and sign" pipeline to migrate DTFx.Core, DTFx.AS, and DTFx.AI to 1ES.
A few cut corners to address in a future follow-up:
* the SBOM parameters need further scrutiny, it's possible it is not analyzing the right data
* The build pipeline isn't building ServiceBus and ServiceFabric (it's commented out in the yml for that reason). It's unclear if we want to do that in the Azure Functions-managed 1ES pipeline
* warning CS7035 is being suppressed, which calls out that our assembly version format doesn't follow conventions. Example: ": Error CS7035: The specified version string '2.17.1.167958' does not conform to the recommended format - major.minor.build.revision". 
* Integration tests aren't included yet. This is just building and signing the code.
* CodeQL …
> Migrate to 1ES (first draft)

- src/DurableTask.AzureStorage/MessageManager.cs
DurableTask.AzureStorage v1.x and v2.x use different version of Azure Storage SDK which use different encoding methods. Consequently, when upgrading from v1 to v2, the app may be stuck with queue processing because workers loaded with DTFx.AS v2 cannot successfully read messages encoded with DTFx.AS v1. This PR introduces a hotfix to ensure forward compatibility.
End-to-end test has been made.
> HotFixes: Enable Support for Forward Compatibility  between DTFx.AzureStorage 1.x to 2.x

- .github/workflows/validate-build.yml
As part of 1ES migration - replaces part of the "DTFx Build & Run tests" pipeline with a GitHub action, in particular, the DTFx.Core tests are replaced here. DTFx.AzureStorage cannot be replaced with a GH action until DTFx.AS v2 is released, where Azurite will be compatible with the tests - the current tests depend on the old Azure Storage emulator and that is not compatible with GitHub pipelines (because they run on ARM64)
> Run DTFx.Core tests in GitHub action

- src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
- src/DurableTask.ServiceBus/Tracking/AzureStorageBlobStore.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableClient.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableCompositeTableEntity.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableInstanceStore.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationHistoryEventEntity.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationJumpStartEntity.cs
- src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationStateEntity.cs
- src/DurableTask.ServiceBus/Tracking/BlobStorageClient.cs
- test/DurableTask.ServiceBus.Tests/AzureTableClientTest.cs
- test/DurableTask.ServiceBus.Tests/BlobStorageClientTest.cs
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
- test/DurableTask.ServiceBus.Tests/OrchestrationHubTableClientTests.cs
- The class CloudStorageAccount no longer exists in the new libraries. Therefore, any constructors that leverage it were replaced with new constructors that take an endpoint to the store and a TokenCredentials object
- TableStore entities were able to implement a method that allowed the code to "unpack" complex types to save and load from tables. These methods are no longer available. Instead, a series of public accessors with custom getters and setters are now used to get the same behavior.
- Running DurableTask.ServiceBus.Tests project: Test runs are green via both the pipeline and running tests against a live storage account
> Migrate DurableTask.ServiceBus Table and Blob store SDK from WindowsAzure.Storage to Azure.Data.Tables and Azure.Storage.Blobs

- src/DurableTask.AzureStorage/Storage/QueueMessage.cs
DTFx.AzureStorage v1.x and v2.x use different Azure Storage SDK versions, each with its own encoding method. This PR adds backward compatibility to DTFx.AzureStorage v1.x, ensuring that queue messages created with DTFx.AS v2 remain readable after downgrading to DTFx.AS v1.
The `RawProperty` is an internal attribute of `CloudQueueMessage`, and we use System.Reflection to access it. The included catch block should only be triggered in the scenario described above.
End-to-End tests have been done.
> Enable DTFx.AzureStorage v1.x backward compatibility support

- samples/ManagedIdentitySample/DTFx.AzureStorage v1.x/ConsoleApp.csproj
- samples/ManagedIdentitySample/DTFx.AzureStorage v1.x/Program.cs
- samples/ManagedIdentitySample/DTFx.AzureStorage v1.x/ReadMe.md
- samples/ManagedIdentitySample/DTFx.AzureStorage v2.x/ConsoleApp.csproj
- samples/ManagedIdentitySample/DTFx.AzureStorage v2.x/Program.cs
- samples/ManagedIdentitySample/DTFx.AzureStorage v2.x/ReadMe.md
As titled.  Add samples about how to use identity-based connection with DTFx framework app.
> Add Token Credential Samples with DTFx.AzureStorage v1 and v2

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationHistoryEventEntity.cs
Removed .NET Framework 4.6.2 TFM and upgraded DurableTask.Core version to 3.0.0.
> Remove net462 TFM

- eng/ci/public-build.yml
- eng/templates/test.yml
Part of 1ES migration - allows test to run on ADO
> Add public build (first draft)

- Test/DurableTask.AzureStorage.Tests/Storage/DurableTaskStorageExceptionTests.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Storage/DurableTaskStorageException.cs
The ctor for `DurableTaskStorageException` will throw an exception if the given `RequestFailedException` is `null` or the `ErrorCode` property is `null`. Both cases should be handled gracefully, and this change involves some refactoring to the class.
Included in this change is also an update to libraries including `Azure.Core` which had a vulnerability.
> Fix DurableTaskStorageException Constructor Null Handling

- eng/ci/public-build.yml
- eng/templates/test.yml
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- src/DurableTask.Core/DurableTask.Core.csproj
- src/DurableTask.Core/TaskActivityDispatcher.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- src/DurableTask.Core/Tracing/TraceHelper.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
- test/DurableTask.AzureStorage.Tests/TestHelpers.cs
- test/DurableTask.AzureStorage.Tests/TestTablePartitionManager.cs
- test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
- test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
- test/DurableTask.Core.Tests/RetryInterceptorTests.cs
- test/DurableTask.Core.Tests/app.config
- test/DurableTask.Emulator.Tests/DurableTask.Emulator.Tests.csproj
- test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
The primary goal of this PR is to add a public 1ES ADO testing CI for DTFx.AS v2. This pipeline's results (and a messy development history) can be found here: https://dev.azure.com/azfunc/public/_build?definitionId=881&_a=summary
While migrating our CI pipeline, I encountered previously stable tests becoming flaky, as well as the fact that some tests were previously not running (and were failing once enabled) plus other 1ES-specific idiosyncrasies. This PR aims to resolve them all. 
To help with reviews, I'll add comments throughout the diff to clarify why some part of the code had to be changed. I feel comfortable about most changes except for one: the addition of  `System.Runtime.CompilerServices.Unsafe  v6.0.0` as an explicit dependency in DTFx.Core.
Without this change, some DTFx.Core …
> Add 1ES CI for DTFx.AS v2

- eng/ci/code-mirror.yml
- eng/ci/official-build.yml
- eng/ci/public-build.yml
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
- test/DurableTask.AzureStorage.Tests/TestTablePartitionManager.cs
Replaces: https://github.com/Azure/durabletask/pull/1136/files, which targets `azure-storage-v12` which got _squashed_ when it got merged to main (on @cgillum's recommendation for a clean history on main). I figured that re-creating the PR was the easier path forward, as the other PR's history would need to be rebased and squashed as well.
Also made some minor edits to our pipeline config so the pipelines run on the DTFx.ASv1 "frozen" branch.
> Ensure queue is listened to on a sudden PMv3 restart

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
- test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
- test/DurableTask.AzureStorage.Tests/TestHelpers.cs
- test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
- test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
There's a proposal to upgrade this deps as part of the DTFx.ASv2  / DTFx.Core v3 release. Just putting this out there to run the CI in advance. Let's not merge until we've had time to do an internal discussion
> Rev deps Microsoft.Extensions and System deps to 6.x

- eng/ci/code-mirror.yml
- eng/ci/official-build.yml
As in title, to allow this branch to be code-mirror in 1ES
> Update code-mirror pipeline in durabletask-core-v2 branch

- test/DurableTask.AzureStorage.Tests/TestTablePartitionManager.cs
The test `TestWorkerRestartBeforeLeaseExpired` has been a bit flakey on the CI. I believe the following refactor should make it more deterministic.
> Un-flake table TestWorkerRestartBeforeLeaseExpired test

- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/Correlation/DurableTaskCorrelationTelemetryInitializer.cs
- test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
- test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
- test/DurableTask.Emulator.Tests/DurableTask.Emulator.Tests.csproj
- test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.csproj
Given our recent TFM changes, and that `netcoreapp3.1` is out of support and will _soon_ no longer be the used in Azure Functions' extension bundles, this PR changes our test project to use `.net6.0` as it's TFM over `netcoreapp3.1`. This removes some warnings from our solution, which should help with compliance and reduce "warning fatigue".
> Remove netcoreapp3.1 from tests

- eng/ci/public-build.yml
The public 1ES build is not automatically running on PRs, as it should. This PR attempts to fix that by trying alternative syntax to the `pr:` block of our public 1ES build definition.
It also adds `durabletask-core-v2` to the list of branches we run our nightly CI on.
> Run public build on all PRs, add DTFx.Core v2 branch to public build triggers

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/TestHelpers.cs
In DTFx.AS, we track an orchestration state in the History and Instance tables, which we update independently in a non-transactional way (there are not transactions in Azure Storage tables). Therefore, there exists a race condition where if DTFx.AS crashes after updating the orchestrator state in the History table but before updating the Instance table, the two tables will be out of sync.
In many cases, this is fine: the next orchestrator replay will update the Instance table and bring the two data stores back in sync. **However**, if the orchestrator is in a terminal state as per the History table (e.g. Completed, Failed, Terminated), then we will not get another opportunity to update the Instances table because we will discard any new events for that instanceID (including "Terminate" …
> Add setting to allow replaying terminal orchestrators in DTFx.AS

- eng/ci/public-build.yml
As in title, just adding the public build CI to the `durabletask-core-v2`. With this, all PRs to `durabletask-core-v2` will get a CI build running the tests.
> add public build to durabletask-core-v2

- Test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
- Test/DurableTask.Core.Tests/MessageSorterTests.cs
- Test/DurableTask.Core.Tests/RetryInterceptorTests.cs
- Test/DurableTask.Core.Tests/TaskHubClientTests.cs
- Test/DurableTask.Core.Tests/TestTaskEntityDispatcher.cs
- eng/ci/public-build.yml
- eng/templates/build-steps.yml
- eng/templates/test.yml
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
- test/DurableTask.Core.Tests/CommonTests.cs
- test/DurableTask.Core.Tests/CustomExceptionsTests.cs
- test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
- test/DurableTask.Core.Tests/HttpCorrelationProtocolTraceContextTest.cs
- test/DurableTask.Core.Tests/StackExtensionsTest.cs
- test/DurableTask.Core.Tests/TraceContextBaseTest.cs
- test/DurableTask.Core.Tests/W3CTraceContextTest.cs
This PR contains various fixes to make the public build CI pass in the `durabletask-core-v2` branch. These changes are listed below:
1. It changes various `[TestMethod]` declarations to `DataTestMethod` in the DTFx.Core test project. For some reason I can't explain, the ADO testing infrastructure was unable to _discover_ these tests if they were marked as `[TestMethod]`. This fix is a **hack**, but it works for now and I think it's worth unblocking us. To my knowledge, these two annotations are almost equivalent, except that a `[DataTestMethod]` can be parametrized (as in the test method can take  a parameter such as `extendedSessionsEnabled`), but a `[TestMethod]` cannot. Other than that, they both declare tests.
2. It remove the parallelism of the DTFx.Core unit testing task (previously …
> [durabletask-core-v2] Various fixes to public build for DTFx.Core v2

- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/TestHelpers.cs
Cherry-pick of: https://github.com/Azure/durabletask/pull/1159
to `durabletask-core-v2`
> [Cherry-pick] [durabletask-core-v2] add setting to allow replaying terminal orchestrators (#1159)

- src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As titled. 
DurableTask.ApplicationInsights v0.1.6 -> v2.0.0 as it uses DurableTask.Core v3.0.0. 
DurableTask.AzureStorage v2.0.0- v2.0.1 for new changes in https://github.com/Azure/durabletask/pull/1159
> Update DurableTask.ApplicationInsights and DurableTask.AzureStorage Version

- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
- test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
as titled. 
Azure.Core updated from 1.41.0 to 1.43.0
Azure.Data.Tables updated from 12.8.3 to 12.9.1
Azure.Storage.Blobs updated from 12.20.0 to 12.22.1
Azure.Storage.Queues updated from 12.18.0 to 12.20.0
> Increase Azure Storage SDK version and DTFx.AzureStorage ver

- eng/ci/code-mirror.yml
- eng/ci/official-build.yml
- eng/ci/public-build.yml
This PR adds the branch `neetart/dtfx_sf_pipeline` as an allowed branch to run our ADO pipelines from. We are adding this to test the changes in the branch and will remove the changes once those changes have been tested and merged to `main`.
> Update pipeline branch list to test DurableTask.AzureServiceFabric addition to pipelines

- src/DurableTask.AzureStorage/AnalyticsEventSource.cs
- src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
- src/DurableTask.AzureStorage/Logging/LogEvents.cs
- src/DurableTask.AzureStorage/Logging/LogHelper.cs
- src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
- src/DurableTask.AzureStorage/Messaging/Session.cs
There are certain kinds of high latency investigations that are hard to debug because we don't have the partition ID included in the ProcessingMessage log event. This PR adds that value.
> Add the PartitionId value to the ProcessingMessage log event

- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/3022.
Sometimes a duplicate message for an execution that is already finished is received late, when this execution is already completed. For example, this can happen when a message is in fact processed, but the worker failed to remove it from the queue for any reason, so the message automatically reappears in the queue later, potentially when the execution is already finished. In most cases, this is not a problem, and this message will eventually be discarded without any negative consequences. However, here is a sequence of events that leads to a stuck orchestration:
1. A `TaskScheduled` message is delivered to a worker and the worker that starts executing an activity.
2. After successfully executing an activity, the …
> Don't fail orchestrations on missing blobs from previous executions

- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
- src/DurableTask.AzureStorage/Storage/DurableTaskStorageException.cs
- src/DurableTask.AzureStorage/Storage/Queue.cs
Fixes #1196 
This issue was discovered as part of investigating ICM#608312432. More details in the issue description. The fix is to retry the delete operation if it fails due to a pop-receipt mismatch. This PR also makes small logging improvements that should help make these kinds of problems easier to diagnose.
I created a console app to reproduce the problem locally and confirm the error details for this kind of scenario.
> Fix renew/delete race in DT.AzureStorage

- src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Fixes an `InvalidOperationException` caused by concurrent modifications to `activeOrchestrationSessions` while `IsControlQueueProcessingMessages` is enumerating its values. This issue could surface as a `PartitionManagerError`.
This method is called when there are drain tasks, where concurrent access is expected. To ensure thread safety, we now add a lock before enumeration.
> Fix Concurrent Modification Error in IsControlQueueProcessingMessages

- src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj
- src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
- Add a 2-second timeout when calling `ReadAndWriteTableAsync`  at TablePartitionManager.
This helps guard against cases where the read or write hangs silently, as Azure Storage client has its own retry policies. If the timeout is hit, a `PartitionManagerWarning` is logged and the operation is retried.
- Bump DTFx.AzureStorage and DTFx.ApplicationInsights minor to align with the  DTFx.Core version increment.
> Add timeout wehn Read&Write Parititon Table 

- Test/DurableTask.Core.Tests/VersionSettingsTests.cs
- src/DurableTask.Core/Settings/VersioningSettings.cs
- src/DurableTask.Core/TaskHubWorker.cs
- src/DurableTask.Core/TaskOrchestrationDispatcher.cs
- test/DurableTask.AzureStorage.Tests/AutoStartOrchestrationCreator.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/TestHelpers.cs
- test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs
This commit adds versioning similar to the feature created in durabletask-dotnet. This portion of versioning allows for an orchestration to be failed or abandonned based on the configuration provided.
The actual configuration will be provided in a follow-up PR in the web extensions as it should be handled through the host.json file.
> Add versioning to DTFx orchestration dispatch

- src/DurableTask.AzureStorage/Partitioning/BlobPartitionLeaseManager.cs
- src/DurableTask.AzureStorage/Storage/Table.cs
- src/DurableTask.AzureStorage/Storage/TableQueryResponse.cs
While writing some Kusto queries for our dashboard, I noticed that we have all zeros for table storage *read* metrics. This is likely a regression from when we swapped Azure Storage SDKs, which required a big code refactor. It's important that we fix this so that we have an accurate idea of the amount of data we're reading from table storage, which appears to be a contributing factor to several incidents.
I added some tiny code cleanup changes in this PR as well, but the main focus is on adding the missing table storage read metrics.
> Add missing table storage read metrics

- src/DurableTask.AzureStorage/MessageManager.cs
- src/DurableTask.AzureStorage/Storage/BlobContainer.cs
- test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
- test/DurableTask.AzureStorage.Tests/MessageManagerTests.cs
When the instanceId contains special characters like '|',' :', or spaces, the generated blob URL becomes invalid because these characters are not allowed unescaped in a URI. This results in the orchestrator returning a blob URL instead of the expected large message content. This PR fixes it by escaping invalid characters when constructing the blob URL.
Solves https://github.com/orgs/Azure/projects/745/views/1?pane=issue&itemId=96361588&issue=Azure%7Cazure-functions-durable-extension%7C3010
> Fix blob URL handling for large messages with special characters in instanceId

- src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
This PR fixes several issues on partition manager v3:
- The drain reason was always logged as "Shutdown," even when caused by lease loss. This is fixed by passing a CloseReason reason argument to CheckDrainTask.
- When draining completes and the lease is released, the worker incorrectly resumes listening to the queue. This is fixed by adding a !ReleasedPartition check to the isRenewingToDrainQueue logic.
> Fix DrainAsync Reason at Logging and Prevent Queue Listening During Partition Release

- src/DurableTask.Core/TaskHubClient.cs
Fixed a bug in `CreateOrchestrationInstanceAsync` where the `startAt` parameter was incorrectly passed as the 8th argument to `InternalCreateOrchestrationInstanceWithRaisedEventAsync`, which expects `startAt` as the 9th parameter.
Updated the method call to correctly pass `startAt` as the 9th argument, preserving the correct order of optional parameters
> Fix parameter ordering bug in TaskHubClient.cs

- src/DurableTask.Core/Entities/ClientEntityHelpers.cs
- src/DurableTask.Core/Entities/OrchestrationEntityContext.cs
This PR introduced breaking changes in that two public methods (ClientEntityHelpers.EmitOperationSignal and OrchestrationEntityContext.EmitRequestMessage) were changed to include optional parameters. Instead, new methods should have been made with these optional parameters and the old methods with the existing method signatures retained. This PR reverts to the old method signatures and introduces the signatures with optional parameters as new methods (which the old methods simply call, passing null for the new parameters).
> Reverting breaking change regarding methods with optional parameters

- src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs
This PR disables Azure Storage distributed tracing by default.
.NET Isolated DF app without disabling storage tracing:
.NET Isolated DF app after disabling storage tracing (tested with the change in this PR):
> Disable storage tracing by default

- Directory.Packages.props
- samples/Correlation.Samples/Correlation.Samples.csproj
- samples/Correlation.Samples/DurableTaskCorrelationTelemetryInitializer.cs
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj
- test/DurableTask.ServiceBus.Tests/OrchestrationHubTableClientTests.cs
The main issues to be resolved are older versions of System.Text.Json (6.0.9) and Microsoft.Owin (2.0.2), which are brought in via transitive dependencies but have known vulnerabilities. These are all minor version updates so hoping they won't result in any breaking changes. 🤞
> Updating dependencies to resolve component governance issues

- src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj
- src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
- src/DurableTask.Core/DurableTask.Core.csproj
- DurableTask.AzureStorage to 2.3.0
- DurableTask.Core to 3.3.0
- DurableTask.ApplicationInsights to 0.5.0
> Bump versions for release

- src/DurableTask.ServiceBus/Tracking/BlobStorageClient.cs
- test/DurableTask.ServiceBus.Tests/BlobStorageClientTest.cs
Migration to Azure.Storage nuget introduced a regression, that we started deleting all containers in a storage account. 
Looks like a regression from 
https://github.com/Azure/durabletask/commit/0af3eca8579eaf69025716738defab91f66676a4#diff-076ce870f6eb747780e059b061509af9841565cac934136074c63bc1cdd43007
> [DurableTask.ServiceBus] List only containers starting with prefix 

- src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
When a race condition occurs between RenewMessage and DeleteMessage, and RenewMessage wins, DeleteMessage fails with a MessageGone error. This happens because DeleteMessage may be using a snapshot of the QueueMessage that is already expired or invalid.
After UpdateMessage, a new QueueMessage instance is created, but DeleteMessage might still reference the old instance and its outdated pop receipt. To prevent this, we should always refer to the OriginalQueueMessage, which contains the most up-to-date information.
> Fix Race Condition between RenewMessage and DeleteMessage
