Framework/DurableTaskFramework.csproj, FrameworkUnitTests/DurableTaskFrameworkUnitTests.csproj
Make package paths compatible with using the projects as a git submodule
=> Vn siport phase4

DurableTaskSamples.sln, Framework/ServiceBusOrchestrationService.cs, Framework/Tracking/AzureTableOrchestrationHistoryEventEntity.cs, Framework/Tracking/OrchestrationHistoryEvent.cs, Framework/Tracking/OrchestrationJumpStartEvent.cs, Framework/Tracking/OrchestrationWorkItemEvent.cs, FrameworkUnitTests/app.config, Samples/DurableTaskSamples/App.config, Samples/DurableTaskSamples/DurableTaskSamples.csproj, Samples/DurableTaskSamplesUnitTests/DurableTaskSamplesUnitTests.csproj, Test/TaskHubStressTest/TaskHubStressTest.sln
Add Sequence number to history messages
Add OrchestrationJumpStartEvent
Update secondary solution files to cater for dll name change.
=> Vn siport seqno

Framework/DurableTaskFramework.csproj, Framework/packages.config, FrameworkUnitTests/DurableTaskFrameworkUnitTests.csproj, FrameworkUnitTests/packages.config
Update Azure.Storage to 7.0
Update Azure.ServiceBus to 3.1.7
=> Siport vn storage sb update

Framework/TaskOrchestrationDispatcher.cs, FrameworkUnitTests/DurableTaskCoreFxTest.cs, FrameworkUnitTests/ErrorHandlingTests.cs, FrameworkUnitTests/Mocks/LocalOrchestrationService.cs, FrameworkUnitTests/Mocks/PeekLockSessionQueue.cs, FrameworkUnitTests/TestHelpers.cs
- Fix LocalOrchestrationService/ServiceBusOrchestrationService and re-enable tests
- Fix jumpstart test byt dropping ignore window for tests.
- Add test for detecting UnobservedTaskException
=> Fix LocalOrchestrationService and re-enable tests

src/DurableTask.Framework/History/HistoryEvent.cs, src/DurableTask.Framework/OrchestrationInstance.cs, src/DurableTask.Framework/OrchestrationState.cs, src/DurableTask.Framework/ParentInstance.cs, src/DurableTask.Framework/StateMessage.cs, src/DurableTask.Framework/TaskMessage.cs
for round tripping support in future versions.
=> Make the data contracts implement IExtensibleDataObject interface 

src/DurableTask.Framework/Common/Utils.cs, src/DurableTask.Framework/Exceptions/TaskFailureException.cs, src/DurableTask.Framework/IOrchestrationService.cs, src/DurableTask.Framework/ReflectionBasedTaskActivity.cs, src/DurableTask.Framework/TaskHubClient.cs, src/DurableTask.Framework/Tracing/TraceHelper.cs, src/DurableTask.Framework/Tracking/AzureTableClient.cs, test/DurableTask.ServiceBus.Tests/DynamicProxyTests.cs, test/DurableTask.ServiceBus.Tests/ErrorHandlingTests.cs
Fix create orch bug
Improve TaskFailureException
All tests working, cleanup some todos
=> Test, Logging Improvements

src/DurableTask.Core/Stats/Counter.cs
The Azure Storage provider makes use of the existing `DurableTask.Core.Stats.Counter` class to keep track of various performance metrics. Two methods are added to this class to improve usability for our scenario:
1. **Decrement**: Some counters need to be increased as well as decreased. This is just a wrapper around `Interlocked.Decrement()`.
2. **Reset**: Some counters need to be periodically reported and then reset to make it easier to report change within a time interval. This is simply a wrapper around `Interlocked.Exchange()`.
Please approve. The changes are very straight forward.
=> Added Decrement() and Reset() operations to Counter class.

.gitignore, src/DurableTask.Emulator/LocalOrchestrationService.cs, test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs, test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs, tools/DurableTask.props
Fix hang in Emulator when calling multiple timers within an orchestration.
=> Fix repeat timers in emulator

src/DurableTask.ServiceBus/Tracking/AzureTableInstanceStore.cs
GetOrchestrationStateAsync: get state entities -> none 
OrchProcessor: write state entity 
Jumpstartmanager: get state entity -> found 
Jumpstartmanager: delete jump start entity 
GetOrchestrationStateAsync: get jump start entities -> none
=> Fix race condition in state lookup

Framework/DurableTaskFramework.csproj, Framework/app.config, Framework/packages.config, FrameworkUnitTests/DurableTaskFrameworkUnitTests.csproj, FrameworkUnitTests/app.config, FrameworkUnitTests/packages.config, Samples/DurableTaskSamples/App.config, Samples/DurableTaskSamples/DurableTaskSamples.csproj, Samples/DurableTaskSamples/Program.cs, Samples/DurableTaskSamples/packages.config, Samples/DurableTaskSamplesUnitTests/app.config
Updated the Framework and samples for Newtonsoft 10 migration.
=> Vnext ns10

Test/DurableTask.AzureStorage.Tests/App.config, Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Previously messages were getting deleted as part of the abandon logic, which was not correct and resulted in data loss whenever the dispatcher encountered an exception. This PR resolves that.
Also included in this PR are some improvements with the error handling for batch message operations.
=> Fixed orchestration message abandon logic

DurableTask.sln
Prevented build after a new Clone (re: https://github.com/NuGet/Home/issues/5350)
=> Update casing of project reference

src/DurableTask.Core/Common/Utils.cs, src/DurableTask.Core/RetryInterceptor.cs, src/DurableTask.ServiceBus/Common/ServiceBusUtils.cs
1) Rethrowing exceptions with context
2) Logging address of messaging factory
=> Capturing exception context

Test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs, src/DurableTask.AzureStorage/AnalyticsEventSource.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs, src/DurableTask.AzureStorage/Monitoring/PerformanceHeartbeat.cs
This is to support improved auto-scale for DurableTask.AzureStorage-based function apps (e.g. Durable Functions) in the Azure Functions consumption plan.
This PR primarily covers a utility class within DurableTask.AzureStorage and should not have any impact on the actual runtime.
=> Reimplemented DurableTask.AzureStorage scaling to focus on queue latency

src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
Hello @cgillum,
May I ask you to review this small modification addressing [#264](https://github.com/Azure/azure-functions-durable-extension/issues/264) issue?
Thank you!
=> Fixing issue with Instance table insertion when using Singelton Pattern

src/DurableTask.AzureStorage/AnalyticsEventSource.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs, src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs, src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs
The issue is described in detail here: https://github.com/Azure/azure-functions-durable-extension/issues/295
=> Fixed issue of caching failed task hub creation tasks

Framework/TrackingDispatcher.cs
Add forward compatibility for possible missing Tracking TaskMessage Properties
=> Add forward compatibility for possible missing Tracking TaskMessage Properties

Framework/TaskOrchestrationContext.cs
cherry-pick two commits from master branch:
https://github.com/Azure/durabletask/commit/273c58f74be7d6b9100cb91bfcbdb0585541d888
https://github.com/Azure/durabletask/commit/1b3efef51509e37a3db1e09404eb535fe75dc039
=> Cherry-pick some fix from master

Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, Test/DurableTask.AzureStorage.Tests/TestOrchestrationClient.cs, Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs, src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs, src/DurableTask.Core/History/EventType.cs, src/DurableTask.Core/History/RewindEvent.cs, src/DurableTask.Core/IOrchestrationServiceClient.cs, src/DurableTask.Core/TaskHubClient.cs, src/DurableTask.Emulator/LocalOrchestrationService.cs, src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
- added RewindInstanceAsync in TaskHubClient
- finds last known good state and rewinds data store (updates history and instance tables)
- does not kick off new orchestration
=> Implementation of rewind functionality

Test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs, Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, src/DurableTask.AzureStorage/AnalyticsEventSource.cs, src/DurableTask.AzureStorage/AsyncManualResetEvent.cs, src/DurableTask.AzureStorage/AsyncQueue.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs, src/DurableTask.AzureStorage/DispatchQueue.cs, src/DurableTask.AzureStorage/MessageData.cs, src/DurableTask.AzureStorage/Messaging/ControlQueue.cs, src/DurableTask.AzureStorage/Messaging/MessageCollection.cs, src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs, src/DurableTask.AzureStorage/Messaging/Session.cs, src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs, src/DurableTask.AzureStorage/Messaging/WorkItemQueue.cs, src/DurableTask.AzureStorage/OrchestrationSessionManager.cs, src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs, src/DurableTask.AzureStorage/Partitioning/PartitionManager.cs, src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs, src/DurableTask.AzureStorage/Tracking/InstanceStoreBackedTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/OrchestrationHistory.cs, src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs, src/DurableTask.AzureStorage/Utils.cs
This PR contains some significant performance and reliability improvements for the DurableTask.AzureStorage package for DTFx.  The high-level work item tracking these improvements is https://github.com/Azure/azure-functions-durable-extension/issues/368.
In summary:
- Refactoring of messaging code for improved maintainability
- Instance history prefetch for improved throughput (addresses https://github.com/Azure/azure-functions-durable-extension/issues/387)
- New setting for max concurrent storage operation concurrency for improved TCP connection usage (https://github.com/Azure/azure-functions-durable-extension/issues/389)
- Switched order of history updates and outbound queue message publishing on orchestration completion
- Refactored eTag handling for improved resiliency and …
=> DurableTask.AzureStorage performance and reliability improvements:

Test/DurableTask.Core.Tests/CustomExceptionsTests.cs, src/DurableTask.Core/Exceptions/NonDeterministicOrchestrationException.cs, src/DurableTask.Core/Exceptions/OrchestrationAlreadyExistsException.cs, src/DurableTask.Core/Exceptions/OrchestrationException.cs, src/DurableTask.Core/Exceptions/OrchestrationFrameworkException.cs, src/DurableTask.Core/Exceptions/SubOrchestrationFailedException.cs, src/DurableTask.Core/Exceptions/TaskFailedException.cs, src/DurableTask.Core/Exceptions/TaskFailedExceptionDeserializationException.cs, src/DurableTask.Core/Exceptions/TaskFailureException.cs, src/DurableTask.Core/Exceptions/TypeMissingException.cs
Missing constructor in Exception classes issue #219
=> Missing constructor in Exception classes #219

src/DurableTask.Core/TaskActivityDispatcher.cs
=> DurableTask.Core: Fix process crash caused by uncaught exception

src/DurableTask.AzureStorage/MessageManager.cs
This work is designed to allow the (de) serialization of messages without providing an explicit assembly name. It should not be a breaking change.
This was done to enable new Durable Functions commands in the Azure Functions CLI (https://github.com/Azure/azure-functions-core-tools/pull/838)
=> Allow (de)serialization of messages without explicit assembly name

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Hello @cgillum,
May I ask you when you have time to review the changes in PR adding support for source-link to Durable Task Azure Storage project.
Thank you!
=> Adding support for source-link

src/DurableTask.Core/DurableTask.Core.csproj, tools/DurableTask.props
Hello @cgillum,
May I ask you to review this small PR for adding SourseLink support to `DurableTask.Core` project?
Thank you!
=> Adding SourceLink support to DurableTask.Core project

Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, src/DurableTask.AzureStorage/AnalyticsEventSource.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/Messaging/ControlQueue.cs, src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs, src/DurableTask.AzureStorage/Messaging/Session.cs, src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs, src/DurableTask.AzureStorage/Messaging/WorkItemQueue.cs, src/DurableTask.AzureStorage/Utils.cs
Merging latest from `azure-storage`.
=> DurableTask.AzureStorage updates for v1.4.1

src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
* Fix #245 
* Increment package version number to v1.4.2
=> DurableFunctions.AzureStorage: Fix regression in abandon code path.

src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
Hi @cgillum 
This is the wrong comment. People might confused by the comment. 
I remove it.
=> Remove wrong comment

Test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Core/TaskOrchestrationDispatcher.cs, test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj, test/DurableTask.Emulator.Tests/DurableTask.Emulator.Tests.csproj, test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj, tools/DurableTask.props
* Fixed issues with fast ContinueAsNew (status and orchestration lifetime)
* Updated test framework dependencies
* Updated package versions
* Added some initial test categories for use with Azure Pipelines
=> ContinueAsNew fixes and test updates

DurableTask.sln.DotSettings, Test/DurableTask.AzureStorage.Tests/AzureStorageOrchestrationServiceSettingsTest.cs, Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, Test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj, Test/DurableTask.AzureStorage.Tests/OrchestrationInstanceStatusQueryConditionTest.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs, src/DurableTask.AzureStorage/BackoffPollingHelper.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs, src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs, src/DurableTask.AzureStorage/StorageAccountDetails.cs, src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs, src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs, src/DurableTask.AzureStorage/Tracking/TrackingStoreBase.cs, src/DurableTask.Core/TaskOrchestrationDispatcher.cs, src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs, test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj, test/DurableTask.Emulator.Tests/DurableTask.Emulator.Tests.csproj, test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs, test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj, test/DurableTask.ServiceBus.Tests/InstanceStoreQueryTests.cs, test/DurableTask.ServiceBus.Tests/TaskHubClientTests.cs, tools/DurableTask.props
This PR is a collection of changes that were done in the `azure-storage` branch. All of the changes have been individually reviewed, but need to be moved into the `master` branch so that we can do an official release to nuget.org.
@adarsh1 @simonporter please do a quick scan of these changes to help make sure there's nothing going in that you didn't expect.
Our CI should also run automatically to verify that all tests are passing (minus the ones we explicitly filtered out).
=> Release payload for DT.Core 2.1.0 and DT.AzureStorage 1.5.0

Test/DurableTask.Redis.Tests/DurableTask.Redis.Tests.csproj, Test/DurableTask.Redis.Tests/EndToEndServiceScenarioTests.cs, Test/DurableTask.Redis.Tests/TestHelpers.cs, Test/DurableTask.Redis.Tests/appsettings.json, src/DurableTask.Redis/RedisOrchestrationService.cs, src/DurableTask.Redis/RedisOrchestrationServiceSettings.cs
Add basic integration test structure for Redis provider and implement TaskHub relevant methods of RedisOrchestrationService with tests.
=> Add TaskHub support for Redis provider

Test/DurableTask.AzureStorage.Tests/AutoStartOrchestrationCreator.cs, Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, Test/DurableTask.AzureStorage.Tests/TestOrchestrationHost.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
Bringing in all changes from azure-storage to master for a v1.6.0 release of DurableTask.AzureStorage.
=> DurableTask.AzureStorage v1.6.0 payload

src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/MessageManager.cs
This PR adds the new method for downloading blobs for DurableTask.AzureStorage.
=> DurableTask.AzureStorage: Merge latest into master

Test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj, Test/DurableTask.Redis.Tests/EndToEndServiceScenarioTests.cs, Test/DurableTask.Redis.Tests/SimpleOrchestrations.cs, Test/DurableTask.Redis.Tests/TestHelpers.cs, Test/DurableTask.Redis.Tests/TestOrchestrationClient.cs, Test/DurableTask.Redis.Tests/appsettings.json, src/DurableTask.Core/WorkItemDispatcher.cs, src/DurableTask.Redis/ActivityTaskHandler.cs, src/DurableTask.Redis/DurableTask.Redis.csproj, src/DurableTask.Redis/OrchestrationSessionPartitionHandler.cs, src/DurableTask.Redis/RedisKeyNameResolver.cs, src/DurableTask.Redis/RedisLogger.cs, src/DurableTask.Redis/RedisOrchestrationService.cs, src/DurableTask.Redis/RedisSerializer.cs, src/DurableTask.Redis/RedisTransactionBuilder.cs, src/DurableTask.Redis/WorkerRecycler.cs
Rough draft support for basic orchestrations. Have tested simple orchestration and fairly large Fan-in/Fan-out.
=> DurableTask.Redis: Initial orchestration support

src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
Fixes https://github.com/Azure/azure-functions-durable-extension/issues/774
=> Fix race condition that creates stuck orchestrations in Azure Storage provider

src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs
Preparation for a DurableTask.AzureStorage release.
=> Merge latest from azure-storage into master

DurableTask.sln, Test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs, Test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/MessageManager.cs, src/DurableTask.AzureStorage/Messaging/ControlQueue.cs, src/DurableTask.AzureStorage/Messaging/WorkItemQueue.cs, src/DurableTask.AzureStorage/OrchestrationSessionManager.cs, src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs, src/DurableTask.AzureStorage/TimeoutHandler.cs
Wrapped deadlocking calls in a TimeoutHandler to mitigate deadlock occurring in the 9.3.3 Azure Storage SDK.
fixes #961 https://github.com/Azure/azure-functions-durable-extension/issues/961
=> Deadlock Mitigation

src/DurableTask.AzureStorage/TimeoutHandler.cs
Added check to the TimeoutHandler to prevent FailFast when using a debugger.
resolves #336
=> Added Debugger Check to TimeoutHandler

src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
This PR is meant to resolve issue #310
=> Initializing resources on startup to fix issue #310

src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
=> [AzureServiceFabric] Update Minor version of the DurableTask.AzureServiceFabric

src/DurableTask.AzureStorage/AnalyticsEventSource.cs, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/Messaging/ControlQueue.cs, src/DurableTask.AzureStorage/Messaging/OrchestrationSession.cs, src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs, src/DurableTask.Core/DurableTask.Core.csproj, tools/DurableTask.props
- Added more detail to dequeue tracing
- Fix nuget warnings in package generation
- Upgrade to non-preview version of Microsoft.SourceLink.GitHub
- Minor code cleanup
=> Misc updates for tracing and packaging

src/DurableTask.Core/OrchestrationContext.cs, src/DurableTask.Core/TaskOrchestrationContext.cs
related to https://github.com/Azure/azure-functions-durable-extension/issues/1155
=> Added DataConverter property to OrchestrationContext to allow for custom serializer settings

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, tools/DurableTask.props
=> Updated Versions

src/DurableTask.Core/OrchestrationContext.cs, src/DurableTask.Core/TaskOrchestrationContext.cs
Separated message and error JsonDataConverters in OrchestrationContext to allow for custom message and error settings.
=> Added error JsonDataConverter property to OrchestrationContext

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Redis/DurableTask.Redis.csproj, tools/DurableTask.props
DurableTask.Core 2.2.3 -> DurableTask.Core 2.2.4
DurableTask.Emulator 2.2.3 -> DurableTask.Emulator 2.2.4
DurableTask.Redis 0.1.3-alpha -> DurableTask.Redis 0.1.4-alpha
DurableTask.AzureStorage 1.7.4 -> DurableTask.AzureStorage 1.7.5
=> Update versions for Durable Functions extension v2.2.1

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Redis/DurableTask.Redis.csproj, tools/DurableTask.props
DurableTask.Core 2.2.4 -> DurableTask.Core 2.2.5
DurableTask.Emulator 2.2.4 -> DurableTask.Emulator 2.2.5
DurableTask.Redis 0.1.4-alpha -> DurableTask.Redis 0.1.5-alpha
DurableTask.AzureStorage 1.7.5 -> DurableTask.AzureStorage 1.7.6
=> Update version for Durable Functions extension v2.2.2

src/DurableTask.AzureStorage/README.md
Some updates to the DurableTask.AzureStorage README that I had on my local machine for a while.
=> DurableTask.AzureStorage README updates

src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
I found this issue while investigating https://github.com/Azure/azure-functions-durable-extension/issues/1365. The impact of the bug is that we fail to properly abandon messages if they have high dequeue counts. It's a pretty simple fix.
=> DurableTask.AzureStorage: Fix int overflow bug in abandon path

src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs, src/DurableTask.ServiceBus/Settings/ServiceBusConnectionSettings.cs
Adding possibility to use Managed Identity or other type of identity authentication with DurableTask.ServiceBus
Resolves https://github.com/Azure/durabletask/issues/414
=> Add Managed Identity support for DurableTask.ServiceBus

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, tools/DurableTask.props
Routine PR, dependencies for: https://github.com/Azure/azure-functions-durable-extension/pull/1655
=> Update versions for extension-release 2.4.1

src/DurableTask.AzureStorage/MessageManager.cs, src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs, src/DurableTask.AzureStorage/Tracking/KeySanitation.cs, src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs, test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs, test/DurableTask.AzureStorage.Tests/KeySanitationTests.cs
Sanitize the instance ids used as partition keys, using an escape mechanism
=> Sanitize the instance ids used as partition keys (#481)

src/DurableTask.Framework/DurableTask.Framework.nuspec, src/DurableTask.Framework/Properties/AssemblyInfo.cs, src/DurableTask.Framework/TaskOrchestrationContext.cs, src/DurableTask.ServiceFabric/DurableTask.ServiceFabric.nuspec
Multiple ExecutionCompletedEvents possible when orchestration termination and completion happens at the same time.
=> [DurableTaskCore] Fix the issue "Multiple ExecutionCompletedEvent found, potential corruption in state storage"

src/DurableTask.ServiceBus/Common/Abstraction/ServiceBusAbstraction.cs
=> Additional exception handling to catch timeout exception from AcceptMessageSessionAsync

src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/Partitioning/BlobLease.cs, src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs, src/DurableTask.AzureStorage/Partitioning/ILeaseManager.cs, src/DurableTask.AzureStorage/Partitioning/Lease.cs, src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs, src/DurableTask.AzureStorage/Partitioning/LegacyPartitionManager.cs, src/DurableTask.AzureStorage/Partitioning/SafePartitionManager.cs, test/DurableTask.AzureStorage.Tests/AzureStorageScaleTests.cs, test/DurableTask.AzureStorage.Tests/TestHelpers.cs
Reverts Azure/durabletask#513 due to performance regressions.
=> Revert "Reduce storage IO costs for partition management"

src/DurableTask.Redis/DurableTask.Redis.csproj
Incremented Redis Version to 0.1.9-alpha
=> Imcremented Redis Version

tools/DurableTask.props
=> Increment DurableTask.Core patch version to 2.5.5

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Prepare for a hotfix release with PRs #560, #568 and #574.
=> Prepare DurableTask.AzureStorage for v1.8.8 release

src/DurableTask.Core/TaskActivityDispatcher.cs
Quick change to set the current activity _before_ running the middleware pipeline. This allows for accessing `Activity.Current` during the middleware. Otherwise it is `null` until the `TaskActivity` is actually executed.
=> TaskActivityDispatcher -> set activity to current before middleware

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Incremented DT-AzureStorage from 1.8.9 to 1.9.0.
=> Incremented AzureStorage version

src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs
Fixed a string format mistake in a log message.
=> Fixed string format

src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
Removed additional noisy log. Related to this change: https://github.com/Azure/durabletask/pull/586
=> Removed additional noisy log

src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs, src/DurableTask.AzureStorage/Messaging/ControlQueue.cs, src/DurableTask.AzureStorage/OrchestrationSessionManager.cs, src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
Added a catch block to the dequeue loop to prevent unhandled exceptions from stopping the dequeue loop.
Added CloseReason to logs when removing control queues.
=> Added catch block in dequeue loop, improved logging

src/DurableTask.ServiceBus/Tracking/AzureTableClient.cs, src/DurableTask.ServiceBus/Tracking/AzureTableInstanceStore.cs, src/DurableTask.ServiceBus/Tracking/BlobStorageClient.cs
Modify AzureTableInstanceStore & AzureTableClient
=> Add CloudStorageAccount support in AzureTableInstanceStore

src/DurableTask.Core/Logging/StructuredLogEvent.cs
This PR changes the value type of `SharedPropertiesCache` from `ConcurrentDictionary` to a regular `Dictionary`. 
The reasoning for this is that once the dictionary is created it's only read. Additionally, `.Values` and `.Keys` might be used by the logger and for `ConcurrentDictionary` these are full blocking properties. With dictionary, they are not
=> StructuredLogEvent uses regular Dictionary now

src/DurableTask.AzureStorage/TimeoutHandler.cs
This PR resolves #676.
This PR resets the `NumTimeoutsHit` count in `TimeoutHandler`, to avoid long-running processes from being impacted by sporadic timeouts.
=> Reset NumTimeoutsHit periodically

src/DurableTask.AzureStorage/AnalyticsEventSource.cs, src/DurableTask.AzureStorage/Logging/LogEvents.cs, src/DurableTask.AzureStorage/Logging/LogHelper.cs, src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
Include LeaseType in lease-stealing flow. This should make it easier to troubleshoot lease-stealing flows.
=> Include LeaseType in lease-stealing flow

samples/DurableTask.Samples/DurableTask.Samples.csproj, src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj, src/DurableTask.AzureStorage/.editorconfig, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.AzureStorage/Storage/Queue.cs, src/DurableTask.Core/DurableTask.Core.csproj, src/DurableTask.Core/TaskOrchestrationContext.cs, src/DurableTask.Emulator/DurableTask.Emulator.csproj, src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, test/DurableTask.AzureServiceFabric.Integration.Tests/DurableTask.AzureServiceFabric.Integration.Tests.csproj, test/DurableTask.AzureServiceFabric.Tests/DurableTask.AzureServiceFabric.Tests.csproj, test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj, test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj, test/DurableTask.Emulator.Tests/DurableTask.Emulator.Tests.csproj, test/DurableTask.ServiceBus.Tests/DurableTask.ServiceBus.Tests.csproj, test/DurableTask.Stress.Tests/DurableTask.Stress.Tests.csproj, test/DurableTask.Test.Orchestrations/DurableTask.Test.Orchestrations.csproj, test/TestFabricApplication/TestApplication.Common/TestApplication.Common.csproj, test/TestFabricApplication/TestApplication.StatefulService/TestApplication.StatefulService.csproj, test/TestFabricApplication/TestApplication/packages.config
- Moving all `net461` targets to `net462`
- Updating `DurableTaks.AzureStorage` version to v1.11.0 to account for this change and some new API surface area changes
- #702 
- #704
- Updating `DurableTask.Core` version to v2.9.0 to account for this and new API surface changes.
- #704
- Added a .editorconfig for the DurableTask.AzureStorage project
Resolves https://github.com/Azure/durabletask/issues/706
=> Update NETFX TFM to 4.6.2

src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs
Ensures lease is properly removed through the LeaseCollectionBalancer instead of using a direct call to the BlobLeaseManager.
=> Updated release call to ensure lease is properly removed

samples/Correlation.Samples/DurableTaskCorrelationTelemetryInitializer.cs, src/DurableTask.Core/DurableTask.Core.csproj, src/DurableTask.Core/OrchestrationContext.cs, src/DurableTask.Core/ReflectionBasedTaskActivity.cs, src/DurableTask.Core/RetryProxy.cs, src/DurableTask.Core/ScheduleProxy.cs, src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
This change addresses #545 by replacing the Dynamity Library with [Castle.Core DynamicProxy](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md).
=> #545 Replace Dynamity with Castle.Core for CreateRetryableClient

src/DurableTask.Core/RetryProxy.cs, test/DurableTask.ServiceBus.Tests/SerializationTests.cs
=> Fix Retry Proxy Bug Causing Test Failures

src/DurableTask.Emulator/LocalOrchestrationService.cs, test/DurableTask.Emulator.Tests/EmulatorFunctionalTests.cs
- Adding support for orchestration tags in DurableTask.Emulator
- Issue #810
=> Add support for orchestration tags

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As in title, to better indicate that this will be a preview release.
=> Update version of AzureStorage v2 to include version suffix

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
=> Update Version 1.13.4

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Core/DurableTask.Core.csproj
Part of: https://github.com/Azure/azure-functions-durable-extension/issues/2405
For DF Extension 2.9.3 release.
=> Increase DTFx.Core and DTFx.AS versions

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
=> increase azureStorage to 1.13.8

Test/DurableTask.AzureStorage.Tests/TestTablePartitionManager.cs, src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
@nytiannn These are mostly stylistic edits for your current partition manager PR (naming, whitespace, removing redundancies, etc.). Please review feel free to merge if you like all of them or start discussions if there are some that you don't understand or agree with. I figured batching my nits in a PR would be more efficient than adding more comments to your PR. :)
=> Suggested edits for table partition manager

src/DurableTask.Core/DurableTask.Core.csproj
Updating DurableTask.Core from v2.13.0 to v2.14.0
=> Update DurableTask.Core version

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Updating DurableTask.AzureStorage from v1.14.0 to v1.15.0
=> Update DurableTask.AzureStorage version

azure-pipelines-release.yml, src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj
Updating DTFx release pipeline and incrementing DurableTask.ApplicationInsights package.
=> Update release pipeline to add DurableTask.ApplicationInsights package

src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
Bump DurableTask.AzureServiceFabric version to 2.3.11
=> Bump DurableTask.AzureServiceFabric version to 2.3.11

samples/DistributedTraceSample/OpenTelemetry/Program.cs, samples/DistributedTraceSample/OpenTelemetry/README.md
This PR updates the `ActivitySource` from `DurableTask` to `DurableTask.Core`.
=> Update ActivitySource in OpenTelemetry sample

src/DurableTask.AzureStorage/EntityTrackingStoreQueries.cs, src/DurableTask.AzureStorage/Tracking/OrchestrationInstanceStatusQueryCondition.cs
Tests found several bugs that are fixed by this PR.
=> Fix bugs in tracking store query implementations

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Core/DurableTask.Core.csproj
As in title, for upcoming release. Related: https://github.com/Azure/azure-functions-durable-extension/issues/2628
=> Increase DTFx.Core and DTFx.AS versions to 2.15.0 and 1.15.1 respectively

src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj, src/DurableTask.Core/DurableTask.Core.csproj
DT.Core 2.15.0 --> 2.15.1
DT.ApplicationInsights 0.1.1 --> 0.1.2
=> Update DT.Core and DT.ApplicationInsights versions

samples/DistributedTraceSample/OpenTelemetry/Program.cs, samples/DistributedTraceSample/OpenTelemetry/README.md, src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Core/DurableTask.Core.csproj, src/DurableTask.Core/Serializing/DataConverter.cs, src/DurableTask.Core/Serializing/Internal/RawInput.cs, src/DurableTask.Core/TaskHubClient.cs, src/DurableTask.Core/TaskOrchestrationContext.cs, src/DurableTask.Core/Tracing/DistributedTraceContext.cs
This PR is to keep branch `Auzre-Storage-v12` updated with branch `main` since we are going to release a new version v2.11.4.
=> Merge main to Azure-Storage-v12

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Core/DurableTask.Core.csproj
Update versions to prepare for public preview. We will merge to `main` before previewing.
=> Prepare for public preview

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj, src/DurableTask.Core/DurableTask.Core.csproj
Needed to pick up latest fixes for preview release
=> udpate version suffix from preview.1 to preview.2

src/DurableTask.AzureStorage/OrchestrationInstanceStatus.cs, src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
- Properly serialize and deserialize orchestration tags
=> Fix Tags Using New Table SDK

src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj
=> Increment DurableTask.ApplicationInsights version

src/DurableTask.Core/DurableTask.Core.csproj
Routine PR for the v2.13.1 release.
=> Increase DurableTask.Core to 2.16.1

src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
AS titled. Routine PR for v2.13.1 release.
=> Increase AzureStorage and ApplicationInsights package version

README.md
Adds link to https://github.com/kaushiksk/durabletask-samples which has detailed samples for various kinds of scenarios with capabilities to see disaster recovery scenarios in action, as well as suspend and resume executing orchestrations.
=> Update README.md with link to samples in durabletask-samples repo

src/DurableTask.Core/DurableTask.Core.csproj, src/DurableTask.Core/Exceptions/OrchestrationException.cs, src/DurableTask.Core/FailureDetails.cs, src/DurableTask.Core/OrchestrationContext.cs, src/DurableTask.Core/TaskOrchestrationContext.cs, src/DurableTask.Core/TaskOrchestrationExecutor.cs, test/DurableTask.Core.Tests/ExceptionHandlingIntegrationTests.cs
Reverts Azure/durabletask#1074
=> Revert "Update Azure Storage Track2 branch with main branch"

src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As titled. 
DTFx.AzureStorage  v1.17.1 -> v1.17.2
DTFx.ApplicationInsights v0.1.4 ->v0.1.5 
DTFx.Core has been updated as v2.17.0 from v2.16.1 in PR #1067
=> Increase DTFx.AzureStorage and DTFx.ApplicationInsights

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As titled. Since we merged the latest changes from main branch, upgrade the version suffix to preview .6
=> Increase DTFx.AS version suffix to preview.6

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As titled. Routine PR for durable functions v3 GA.
=> Upgrade Azure Storage SDK to the Latest

src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As titled. Since DTFx.Core is increased to v2.17.1, increase DTFx.AzureStorage from v1.17.2 to v1.17.3, and DTFx.ApplicationInsights from v0.1.5 to v0.1.6
=> Increase DTFx.AzureStorage and DTFx.ApplicationInsights version

src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
For hotfix release as 4.0.0 release accidentally depended on  ci-build of DTFx.AS
=> rev DTFx.SB to 4.0.1

.github/workflows/validate-build.yml, src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs
Updating tests to run DT.AS tests and also updating the default value of `UseTablePartitionManagement` to true.
=> Update validate-build.yml to run DT.AS unit tests and change default value of UseTablePartitionManagement to true

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As in title, in preparation for release
=> Rev azStorage version to 1.17.4

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As in title, in preparation for release
=> Remove version in prep for DT.Core v3 and DT.AS v2 release

Directory.Build.targets, DurableTask.sln
As in title, cherry-pick of: https://github.com/Azure/durabletask/pull/1147
=> [Cherry-pick to durabletask-core-v2] Add source link reconstruction (#1147)

src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
As in title, for upcoming release.
=> Rev DTFx.AS to 1.17.5

eng/templates/build.yml, src/DurableTask.AzureServiceFabric/DurableTask.AzureServiceFabric.csproj
Adding DTFx SF provider package to DevOps pipeline. Bumping up Newtonsoft.JSON package version to address vulnerabilities.
=> Adding DTFx SF provider package to DevOps pipeline

test/DurableTask.AzureStorage.Tests/DurableTask.AzureStorage.Tests.csproj
VS refuses to load this project without the fix.
=> Fix DurableTask.AzureStorage.Tests.csproj

src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj, src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
Microsoft.Azure.DurableTask.AzureStorage 2.1.0 -> 2.2.0
Microsoft.Azure.DurableTask.ApplicationInsights 0.3.0 -> 0.4.0
=> Update DurableTask.AzureStorage to 2.2.0 and DurableTask.ApplicationInsights to 0.4.0

eng/templates/build.yml, src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
=> Release DurableTask.ServiceBus v4.0.2 and Add ServiceBus Pacakge to Release Pipeline
